//
// Generated by JSON Model Compiler version 2
// see https://github.com/clairey-zx81/json-model
//

import json_model.*;
import java.util.Map;
import java.util.Set;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.regex.Pattern;
import java.util.regex.Matcher;

@SuppressWarnings("unchecked")
public class str_eq extends ModelChecker
{
    static public final String VERSION = "2";

    public Map<String, Checker> str_eq_map_pmap;

    // check $ (.)
    public boolean json_model_1(Object val, Path path, Report rep)
    {
        // .
        if (! json.isObject(val))
        {
            if (rep != null) rep.addEntry("not an object [.]", path);
            return false;
        }
        boolean res;
        Iterator<String> prop_loop = json.objectIterator(val);
        while (prop_loop.hasNext())
        {
            String prop = prop_loop.next();
            Object pval = json.objectValue(val, prop);
            Path lpath_0 = new Path(prop, path);
            if (prop.compareTo("") == 0)
            {
                // handle may  property
                // .''
                res = true;
                continue;
            }
            else if (prop.compareTo("hello") == 0)
            {
                // handle may hello property
                // .hello
                res = true;
                continue;
            }
            else if (prop.compareTo("quite-a-long-property-name") == 0)
            {
                // handle may quite-a-long-property-name property
                // .'quite-a-long-property-name'
                res = true;
                continue;
            }
            if (rep != null) rep.addEntry("unexpected prop [.]", (path != null ? lpath_0 : null));
            return false;
        }
        return true;
    }


    public void init(JSON json)
    {
        if (!initialized)
        {
            try {
            str_eq_map_pmap = new HashMap<String, Checker>();
            str_eq_map_pmap.put("", new Checker() { public boolean call(Object o, Path p, Report r) { return json_model_1(o, p, r);} });
                super.init(json);
            }
            catch (Exception e) {
                throw new Error("cannot initialized model checker: " + e);
            }
        }
    }

    public void free()
    {
        if (initialized)
        {
            super.free();
            str_eq_map_pmap = null;
        }
    }

    public Checker get(String name)
    {
        return str_eq_map_pmap.get(name);
    }

    public Set<String> models()
    {
        return str_eq_map_pmap.keySet();
    }

    static public void main(String[] args) throws Exception
    {
        ModelChecker checker = new str_eq();
        Main.main("str_eq", checker, VERSION, args);
    }
}
