//
// Generated by JSON Model Compiler version 2
// see https://github.com/clairey-zx81/json-model
//

import json_model.*;
import java.util.Map;
import java.util.Set;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.regex.Pattern;
import java.util.regex.Matcher;

@SuppressWarnings("unchecked")
public class x2o_0 extends ModelChecker
{
    static public final String VERSION = "2";

    Set<Object> _jm_cst_0_set;
    Map<Object, Checker> _jm_map_0_cmap;
    public Map<String, Checker> x2o_0_map_pmap;

    // object .'|'.0
    public boolean _jm_obj_0(Object val, Path path, Report rep)
    {
        // check close must only props
        if (! json.isObject(val))
        {
            if (rep != null) rep.addEntry("not an object [.'|'.0]", path);
            return false;
        }
        if (json.objectSize(val) != 1)
        {
            if (rep != null) rep.addEntry("bad property count [.'|'.0]", path);
            return false;
        }
        Path lpath;
        Object pval;
        boolean res;
        if (! ((pval = json.objectValue(val, "t")) != null))
        {
            if (rep != null) rep.addEntry("missing mandatory prop <t> [.'|'.0]", path);
            return false;
        }
        lpath = new Path("t", path);
        // .'|'.0.t
        res = json.isString(pval) && json.asString(pval).compareTo("a") == 0;
        if (! res)
        {
            if (rep != null) rep.addEntry("unexpected a [.'|'.0.t]", (path != null ? lpath : null));
            if (rep != null) rep.addEntry("unexpected value for mandatory prop <t> [.'|'.0]", (path != null ? lpath : null));
            return false;
        }
        return true;
    }


    // object .'|'.1
    public boolean _jm_obj_1(Object val, Path path, Report rep)
    {
        // check close must only props
        if (! json.isObject(val))
        {
            if (rep != null) rep.addEntry("not an object [.'|'.1]", path);
            return false;
        }
        if (json.objectSize(val) != 1)
        {
            if (rep != null) rep.addEntry("bad property count [.'|'.1]", path);
            return false;
        }
        Path lpath;
        Object pval;
        boolean res;
        if (! ((pval = json.objectValue(val, "t")) != null))
        {
            if (rep != null) rep.addEntry("missing mandatory prop <t> [.'|'.1]", path);
            return false;
        }
        lpath = new Path("t", path);
        // .'|'.1.t
        res = json.isScalar(pval) && _jm_cst_0_set.contains(pval);
        if (! res)
        {
            if (rep != null) rep.addEntry("value not in enum [.'|'.1.t.'|']", (path != null ? lpath : null));
            if (rep != null) rep.addEntry("unexpected value for mandatory prop <t> [.'|'.1]", (path != null ? lpath : null));
            return false;
        }
        return true;
    }

    // object .'|'.2
    public boolean _jm_obj_2(Object val, Path path, Report rep)
    {
        // check close must only props
        if (! json.isObject(val))
        {
            if (rep != null) rep.addEntry("not an object [.'|'.2]", path);
            return false;
        }
        if (json.objectSize(val) != 1)
        {
            if (rep != null) rep.addEntry("bad property count [.'|'.2]", path);
            return false;
        }
        Path lpath;
        Object pval;
        boolean res;
        if (! ((pval = json.objectValue(val, "t")) != null))
        {
            if (rep != null) rep.addEntry("missing mandatory prop <t> [.'|'.2]", path);
            return false;
        }
        lpath = new Path("t", path);
        // .'|'.2.t
        // generic xor list
        long xc_0 = 0;
        boolean xr_0;
        // .'|'.2.t.'^'.0
        xr_0 = json.isString(pval);
        if (xr_0)
        {
            xc_0 += 1;
        }
        else
        {
            if (rep != null) rep.addEntry("unexpected string [.'|'.2.t.'^'.0]", (path != null ? lpath : null));
        }
        // .'|'.2.t.'^'.1
        xr_0 = json.isString(pval) && json.asString(pval).compareTo("a") == 0;
        if (xr_0)
        {
            xc_0 += 1;
        }
        else
        {
            if (rep != null) rep.addEntry("unexpected _a [.'|'.2.t.'^'.1]", (path != null ? lpath : null));
        }
        if (xc_0 <= 1)
        {
            // .'|'.2.t.'^'.2
            xr_0 = json.isString(pval) && json.asString(pval).compareTo("b") == 0;
            if (xr_0)
            {
                xc_0 += 1;
            }
            else
            {
                if (rep != null) rep.addEntry("unexpected _b [.'|'.2.t.'^'.2]", (path != null ? lpath : null));
            }
        }
        if (xc_0 <= 1)
        {
            // .'|'.2.t.'^'.3
            xr_0 = json.isString(pval) && json.asString(pval).compareTo("c") == 0;
            if (xr_0)
            {
                xc_0 += 1;
            }
            else
            {
                if (rep != null) rep.addEntry("unexpected _c [.'|'.2.t.'^'.3]", (path != null ? lpath : null));
            }
        }
        res = xc_0 == 1;
        if (res)
        {
            if (rep != null) rep.clearEntries();
        }
        else
        {
            if (rep != null) rep.addEntry("not one model match [.'|'.2.t.'^']", (path != null ? lpath : null));
            if (rep != null) rep.addEntry("unexpected value for mandatory prop <t> [.'|'.2]", (path != null ? lpath : null));
            return false;
        }
        return true;
    }


    // check $ (.)
    public boolean json_model_1(Object val, Path path, Report rep)
    {
        boolean res;
        // xor-to-or with not constant exclusion
        // .
        boolean iso_0 = json.isObject(val);
        res = iso_0;
        if (res)
        {
            if (json.objectHasProp(val, "t"))
            {
                Object tag_0 = json.objectValue(val, "t");
                Checker fun_0 = _jm_map_0_cmap.get(tag_0);
                if (fun_0 != null)
                {
                    res = fun_0.call(val, path, rep);
                }
                else
                {
                    res = false;
                    if (rep != null) rep.addEntry("tag <t> value not found [.'|']", path);
                }
            }
            else
            {
                res = false;
                if (rep != null) rep.addEntry("tag prop <t> is missing [.'|']", path);
            }
        }
        else
        {
            if (rep != null) rep.addEntry("value is not an object [.'|']", path);
        }
        if (! res)
        {
            // .'|'.2
            res = _jm_obj_2(val, path, rep);
            if (! res)
            {
                if (rep != null) rep.addEntry("unexpected element [.'|'.2]", path);
            }
        }
        return res;
    }


    public void init(JSON json)
    {
        if (!initialized)
        {
            try {
            _jm_cst_0_set = new HashSet<Object>();
            _jm_cst_0_set.add(json.safeJSON("\"b\""));
            _jm_cst_0_set.add(json.safeJSON("\"c\""));
            _jm_map_0_cmap = new HashMap<Object, Checker>();
            _jm_map_0_cmap.put(json.safeJSON("\"a\""), new Checker() { public boolean call(Object o, Path p, Report r) { return _jm_obj_0(o, p, r);} });
            _jm_map_0_cmap.put(json.safeJSON("\"b\""), new Checker() { public boolean call(Object o, Path p, Report r) { return _jm_obj_1(o, p, r);} });
            _jm_map_0_cmap.put(json.safeJSON("\"c\""), new Checker() { public boolean call(Object o, Path p, Report r) { return _jm_obj_1(o, p, r);} });
            x2o_0_map_pmap = new HashMap<String, Checker>();
            x2o_0_map_pmap.put("", new Checker() { public boolean call(Object o, Path p, Report r) { return json_model_1(o, p, r);} });
                super.init(json);
            }
            catch (Exception e) {
                throw new Error("cannot initialized model checker: " + e);
            }
        }
    }

    public void free()
    {
        if (initialized)
        {
            super.free();
            _jm_cst_0_set = null;
            _jm_map_0_cmap = null;
            x2o_0_map_pmap = null;
        }
    }

    public Checker get(String name)
    {
        return x2o_0_map_pmap.get(name);
    }

    public Set<String> models()
    {
        return x2o_0_map_pmap.keySet();
    }

    static public void main(String[] args) throws Exception
    {
        ModelChecker checker = new x2o_0();
        Main.main("x2o_0", checker, VERSION, args);
    }
}
