//
// Generated by JSON Model Compiler version 2
// see https://github.com/clairey-zx81/json-model
//

// regular expression engine
#include <stddef.h>
#include <cre2.h>

#include <json-model.h>
#define JSON_MODEL_VERSION "2"

static bool json_model_2(const json_t *val, jm_path_t *path, jm_report_t *rep);
static INLINE bool _jm_cst_0_str_test(const char *);
static bool json_model_3(const json_t *val, jm_path_t *path, jm_report_t *rep);
static bool json_model_4(const json_t *val, jm_path_t *path, jm_report_t *rep);
static jm_constmap_t _jm_map_0_tab[3];
static bool json_model_1(const json_t *val, jm_path_t *path, jm_report_t *rep);
jm_propmap_t check_model_map_tab[4];
const size_t check_model_map_size = 4;

// check $a (.'$a')
static bool json_model_2(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    // .'$a'
    if (unlikely(! json_is_object(val)))
    {
        if (rep) jm_report_add_entry(rep, "not an object [.'$a']", path);
        return false;
    }
    bool res;
    int64_t must_count = 0;
    const char *prop;
    json_t *pval;
    json_object_foreach((json_t *) val, prop, pval)
    {
        jm_path_t lpath_0 = (jm_path_t) { prop, 0, path, NULL };
        if (likely(jm_str_eq_2(prop, 0x00000074)))
        {
            // handle must t property
            must_count += 1;
            // .'$a'.t
            res = json_is_string(pval) && jm_str_eq_2(json_string_value(pval), 0x00000061);
            if (unlikely(! res))
            {
                if (rep) jm_report_add_entry(rep, "unexpected a [.'$a'.t]", (path ? &lpath_0 : NULL));
                if (rep) jm_report_add_entry(rep, "invalid mandatory prop value [.'$a'.t]", (path ? &lpath_0 : NULL));
                return false;
            }
        }
        else
        {
            if (rep) jm_report_add_entry(rep, "unexpected prop [.'$a']", (path ? &lpath_0 : NULL));
            return false;
        }
    }
    if (unlikely(must_count != 1))
    {
        if (likely(rep != NULL))
        {
            if (! (json_object_get(val, "t") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <t> [.'$a']", path);
            }
        }
        return false;
    }
    return true;
}

static INLINE bool _jm_cst_0_str_test(const char *s)
{
    return jm_str_eq_2(s, 0x00000062)  // "b"
        || jm_str_eq_2(s, 0x00000063)  // "c"
    ;
}

// check $bc (.'$bc')
static bool json_model_3(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    // .'$bc'
    if (unlikely(! json_is_object(val)))
    {
        if (rep) jm_report_add_entry(rep, "not an object [.'$bc']", path);
        return false;
    }
    bool res;
    int64_t must_count = 0;
    const char *prop;
    json_t *pval;
    json_object_foreach((json_t *) val, prop, pval)
    {
        jm_path_t lpath_1 = (jm_path_t) { prop, 0, path, NULL };
        if (likely(jm_str_eq_2(prop, 0x00000074)))
        {
            // handle must t property
            must_count += 1;
            // .'$bc'.t
            res = json_is_string(pval) && _jm_cst_0_str_test(json_string_value(pval));
            if (unlikely(! res))
            {
                if (rep) jm_report_add_entry(rep, "value not in enum [.'$bc'.t.'|']", (path ? &lpath_1 : NULL));
                if (rep) jm_report_add_entry(rep, "invalid mandatory prop value [.'$bc'.t]", (path ? &lpath_1 : NULL));
                return false;
            }
        }
        else
        {
            if (rep) jm_report_add_entry(rep, "unexpected prop [.'$bc']", (path ? &lpath_1 : NULL));
            return false;
        }
    }
    if (unlikely(must_count != 1))
    {
        if (likely(rep != NULL))
        {
            if (! (json_object_get(val, "t") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <t> [.'$bc']", path);
            }
        }
        return false;
    }
    return true;
}

// check $Nabc (.'$Nabc')
static bool json_model_4(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    // .'$Nabc'
    if (unlikely(! json_is_object(val)))
    {
        if (rep) jm_report_add_entry(rep, "not an object [.'$Nabc']", path);
        return false;
    }
    bool res;
    int64_t must_count = 0;
    const char *prop;
    json_t *pval;
    json_object_foreach((json_t *) val, prop, pval)
    {
        jm_path_t lpath_2 = (jm_path_t) { prop, 0, path, NULL };
        if (likely(jm_str_eq_2(prop, 0x00000074)))
        {
            // handle must t property
            must_count += 1;
            // .'$Nabc'.t
            // generic xor list
            int64_t xc_0 = 0;
            // .'$Nabc'.t.'^'.0
            bool xr_0 = json_is_string(pval);
            if (unlikely(xr_0))
                xc_0 += 1;
            else
            {
                if (rep) jm_report_add_entry(rep, "unexpected string [.'$Nabc'.t.'^'.0]", (path ? &lpath_2 : NULL));
            }
            // .'$Nabc'.t.'^'.1
            xr_0 = json_is_string(pval) && jm_str_eq_2(json_string_value(pval), 0x00000061);
            if (unlikely(xr_0))
                xc_0 += 1;
            else
            {
                if (rep) jm_report_add_entry(rep, "unexpected _a [.'$Nabc'.t.'^'.1]", (path ? &lpath_2 : NULL));
            }
            if (xc_0 <= 1)
            {
                // .'$Nabc'.t.'^'.2
                xr_0 = json_is_string(pval) && jm_str_eq_2(json_string_value(pval), 0x00000062);
                if (unlikely(xr_0))
                    xc_0 += 1;
                else
                {
                    if (rep) jm_report_add_entry(rep, "unexpected _b [.'$Nabc'.t.'^'.2]", (path ? &lpath_2 : NULL));
                }
            }
            if (xc_0 <= 1)
            {
                // .'$Nabc'.t.'^'.3
                xr_0 = json_is_string(pval) && jm_str_eq_2(json_string_value(pval), 0x00000063);
                if (unlikely(xr_0))
                    xc_0 += 1;
                else
                {
                    if (rep) jm_report_add_entry(rep, "unexpected _c [.'$Nabc'.t.'^'.3]", (path ? &lpath_2 : NULL));
                }
            }
            res = xc_0 == 1;
            if (likely(res))
            {
                if (rep) jm_report_free_entries(rep);
            }
            else
            {
                if (rep) jm_report_add_entry(rep, "not one model match [.'$Nabc'.t.'^']", (path ? &lpath_2 : NULL));
                if (rep) jm_report_add_entry(rep, "invalid mandatory prop value [.'$Nabc'.t]", (path ? &lpath_2 : NULL));
                return false;
            }
        }
        else
        {
            if (rep) jm_report_add_entry(rep, "unexpected prop [.'$Nabc']", (path ? &lpath_2 : NULL));
            return false;
        }
    }
    if (unlikely(must_count != 1))
    {
        if (likely(rep != NULL))
        {
            if (! (json_object_get(val, "t") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <t> [.'$Nabc']", path);
            }
        }
        return false;
    }
    return true;
}

static INLINE jm_check_fun_t _jm_map_0(json_t *val)
{
    jm_constant_t cst;
    jm_set_cst(&cst, val);
    return jm_search_constmap(&cst, _jm_map_0_tab, 3);
}

// check $ (.)
static bool json_model_1(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // xor-to-or with not constant exclusion behind references
    // .
    bool iso_0 = json_is_object(val);
    res = iso_0;
    if (likely(res))
    {
        if (likely(json_object_get(val, "t") != NULL))
        {
            json_t * tag_0 = json_object_get(val, "t");
            jm_check_fun_t fun_0 = _jm_map_0(tag_0);
            if (likely(fun_0 != NULL))
                res = fun_0(val, path, rep);
            else
            {
                res = false;
                if (rep) jm_report_add_entry(rep, "tag <t> value not found [.'|']", path);
            }
        }
        else
        {
            res = false;
            if (rep) jm_report_add_entry(rep, "tag prop <t> is missing [.'|']", path);
        }
    }
    else
    {
        if (rep) jm_report_add_entry(rep, "value is not an object [.'|']", path);
    }
    return res || json_model_4(val, path, rep);
}

jm_check_fun_t check_model_map(const char *pname)
{
    return jm_search_propmap(pname, check_model_map_tab, 4);
}

static bool initialized = false;

const char *check_model_init(void)
{
    if (!initialized)
    {
        initialized = true;
        jm_version_string = JSON_MODEL_VERSION;
        _jm_map_0_tab[0] = (jm_constmap_t) { (jm_constant_t) { cst_is_string, { .s = "a" } }, json_model_2 };
        _jm_map_0_tab[1] = (jm_constmap_t) { (jm_constant_t) { cst_is_string, { .s = "b" } }, json_model_3 };
        _jm_map_0_tab[2] = (jm_constmap_t) { (jm_constant_t) { cst_is_string, { .s = "c" } }, json_model_3 };
        jm_sort_constmap(_jm_map_0_tab, 3);
        check_model_map_tab[0] = (jm_propmap_t) { "", json_model_1 };
        check_model_map_tab[1] = (jm_propmap_t) { "a", json_model_2 };
        check_model_map_tab[2] = (jm_propmap_t) { "bc", json_model_3 };
        check_model_map_tab[3] = (jm_propmap_t) { "Nabc", json_model_4 };
        jm_sort_propmap(check_model_map_tab, 4);
    }
    return NULL;
}

void check_model_free(void)
{
    if (initialized)
        initialized = false;

        // cleanup code
}

/*
 * # API
 *
 * ```c
 * bool error;
 * char *message;
 *
 * bool valid = check(json_value, "model-name", &error, &message);
 *
 * if (message)
 *    free(message), message = NULL;
 * ```
 *
 * - `error` is set of there was an error during initialization or if the model does not exists.
 * - `message` is provided if a non NULL pointer is passed, and must be freed by the caller.
 */
bool
check_model(const json_t *val, const char *name, bool *error, char **reasons)
{
    return jm_generic_entry(check_model_init, check_model_map, val, name, error, reasons);
}
