//
// Generated by JSON Model Compiler version 2
// see https://github.com/clairey-zx81/json-model
//
import 'dart:convert';
import 'dart:io';
import 'dart:core';
// Import the helper library generated nearby
import 'package:json_model_runtime/json_model.dart' as runtime;
import 'package:json_model_runtime/main.dart';

//
// Generated JSON Model Validator
//
const String JSON_MODEL_VERSION = "2";

var check_model_map = <String, Function>{};

// check $ (.)
bool json_model_1(dynamic val, List<dynamic>? path, List<dynamic>? rep)
{
    bool res;
    // not hello, world or !
    // .
    // generic xor list
    int xc_0 = 0;
    // .'^'.0
    bool xr_0 = (val is String);
    if (xr_0)
    {
        xc_0 += 1;
    }
    else
    {
        rep?.add(["unexpected string [.'^'.0]", path]);
    }
    // .'^'.1
    xr_0 = (val is String) && val.compareTo("world") == 0;
    if (xr_0)
    {
        xc_0 += 1;
    }
    else
    {
        rep?.add(["unexpected _world [.'^'.1]", path]);
    }
    if (xc_0 <= 1)
    {
        // .'^'.2
        xr_0 = (val is String) && val.compareTo("!") == 0;
        if (xr_0)
        {
            xc_0 += 1;
        }
        else
        {
            rep?.add(["unexpected _! [.'^'.2]", path]);
        }
    }
    if (xc_0 <= 1)
    {
        // .'^'.3
        xr_0 = (val is String) && val.compareTo("hello") == 0;
        if (xr_0)
        {
            xc_0 += 1;
        }
        else
        {
            rep?.add(["unexpected _hello [.'^'.3]", path]);
        }
    }
    res = xc_0 == 1;
    if (res)
    {
        rep?.clear();
    }
    else
    {
        rep?.add(["not one model match [.'^']", path]);
    }
    return res;
}


// dart_init.dart
class GlobalState {
  static bool initializer = false;
}

Function? check_model_fun(String name) {
  return check_model_map[name];
}


void check_model_init() {
  if (!GlobalState.initializer){
    GlobalState.initializer = true;
  }
        check_model_map[""] = json_model_1;
}

// dart_free.dart
void check_model_free() {
  GlobalState.initializer = true;
}


void main(List<String> args) {
  runValidation(
    args,
    check_model_init,
    check_model_fun,
    check_model_free,
  );
}
