//
// Generated by JSON Model Compiler version 2
// see https://github.com/clairey-zx81/json-model
//

import json_model.*;
import java.util.Map;
import java.util.Set;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.regex.Pattern;
import java.util.regex.Matcher;

@SuppressWarnings("unchecked")
public class xx_1 extends ModelChecker
{
    static public final String VERSION = "2";

    public Map<String, Checker> xx_1_map_pmap;

    // check $ (.)
    public boolean json_model_1(Object val, Path path, Report rep)
    {
        boolean res;
        // not hello, world or !
        // .
        // generic xor list
        long xc_0 = 0;
        boolean xr_0;
        // .'^'.0
        xr_0 = json.isString(val);
        if (xr_0)
        {
            xc_0 += 1;
        }
        else
        {
            if (rep != null) rep.addEntry("unexpected string [.'^'.0]", path);
        }
        // .'^'.1
        xr_0 = json.isString(val) && json.asString(val).compareTo("world") == 0;
        if (xr_0)
        {
            xc_0 += 1;
        }
        else
        {
            if (rep != null) rep.addEntry("unexpected _world [.'^'.1]", path);
        }
        if (xc_0 <= 1)
        {
            // .'^'.2
            xr_0 = json.isString(val) && json.asString(val).compareTo("!") == 0;
            if (xr_0)
            {
                xc_0 += 1;
            }
            else
            {
                if (rep != null) rep.addEntry("unexpected _! [.'^'.2]", path);
            }
        }
        if (xc_0 <= 1)
        {
            // .'^'.3
            xr_0 = json.isString(val) && json.asString(val).compareTo("hello") == 0;
            if (xr_0)
            {
                xc_0 += 1;
            }
            else
            {
                if (rep != null) rep.addEntry("unexpected _hello [.'^'.3]", path);
            }
        }
        res = xc_0 == 1;
        if (res)
        {
            if (rep != null) rep.clearEntries();
        }
        else
        {
            if (rep != null) rep.addEntry("not one model match [.'^']", path);
        }
        return res;
    }


    public void init(JSON json)
    {
        if (!initialized)
        {
            try {
            xx_1_map_pmap = new HashMap<String, Checker>();
            xx_1_map_pmap.put("", new Checker() { public boolean call(Object o, Path p, Report r) { return json_model_1(o, p, r);} });
                super.init(json);
            }
            catch (Exception e) {
                throw new Error("cannot initialized model checker: " + e);
            }
        }
    }

    public void free()
    {
        if (initialized)
        {
            super.free();
            xx_1_map_pmap = null;
        }
    }

    public Checker get(String name)
    {
        return xx_1_map_pmap.get(name);
    }

    public Set<String> models()
    {
        return xx_1_map_pmap.keySet();
    }

    static public void main(String[] args) throws Exception
    {
        ModelChecker checker = new xx_1();
        Main.main("xx_1", checker, VERSION, args);
    }
}
