//
// Generated by JSON Model Compiler version 2
// see https://github.com/clairey-zx81/json-model
//

// regular expression engine
#include <stddef.h>
#include <cre2.h>

#include <json-model.h>
#define JSON_MODEL_VERSION "2"

static bool json_model_2(const json_t *val, jm_path_t *path, jm_report_t *rep);
static bool json_model_1(const json_t *val, jm_path_t *path, jm_report_t *rep);
jm_propmap_t check_model_map_tab[2];
const size_t check_model_map_size = 2;

// check $empty (.'$empty')
static bool json_model_2(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    // .'$empty'
    return json_is_object(val) && json_object_size(val) == 0;
}

// check $ (.)
static bool json_model_1(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    // .
    if (unlikely(! json_is_object(val)))
        return false;
    bool res;
    const char *prop;
    json_t *pval;
    json_object_foreach((json_t *) val, prop, pval)
    {
        uint32_t hash_0 = (*((uint32_t *) (prop))) & 0xffffff;
        if (hash_0 <= 13414)
        {
            if (jm_str_eq_3(prop, 0x00003066))
            {
                // handle may f0 property
                // .f0
                res = json_model_2(pval, NULL, NULL);
                if (unlikely(! res))
                    return false;
                continue;
            }
            else if (jm_str_eq_3(prop, 0x00003166))
            {
                // handle may f1 property
                // .f1
                res = json_model_2(pval, NULL, NULL);
                if (unlikely(! res))
                    return false;
                continue;
            }
            else if (jm_str_eq_3(prop, 0x00003266))
            {
                // handle may f2 property
                // .f2
                res = json_model_2(pval, NULL, NULL);
                if (unlikely(! res))
                    return false;
                continue;
            }
            else if (jm_str_eq_3(prop, 0x00003366))
            {
                // handle may f3 property
                // .f3
                res = json_model_2(pval, NULL, NULL);
                if (unlikely(! res))
                    return false;
                continue;
            }
            else if (jm_str_eq_3(prop, 0x00003466))
            {
                // handle may f4 property
                // .f4
                res = json_model_2(pval, NULL, NULL);
                if (unlikely(! res))
                    return false;
                continue;
            }
        }
        else
        {
            if (jm_str_eq_3(prop, 0x00003566))
            {
                // handle may f5 property
                // .f5
                res = json_model_2(pval, NULL, NULL);
                if (unlikely(! res))
                    return false;
                continue;
            }
            else if (jm_str_eq_3(prop, 0x00003666))
            {
                // handle may f6 property
                // .f6
                res = json_model_2(pval, NULL, NULL);
                if (unlikely(! res))
                    return false;
                continue;
            }
            else if (jm_str_eq_3(prop, 0x00003766))
            {
                // handle may f7 property
                // .f7
                res = json_model_2(pval, NULL, NULL);
                if (unlikely(! res))
                    return false;
                continue;
            }
            else if (jm_str_eq_3(prop, 0x00003866))
            {
                // handle may f8 property
                // .f8
                res = json_model_2(pval, NULL, NULL);
                if (unlikely(! res))
                    return false;
                continue;
            }
            else if (jm_str_eq_3(prop, 0x00003966))
            {
                // handle may f9 property
                // .f9
                res = json_model_2(pval, NULL, NULL);
                if (unlikely(! res))
                    return false;
                continue;
            }
        }
        return false;
    }
    return true;
}

jm_check_fun_t check_model_map(const char *pname)
{
    return jm_search_propmap(pname, check_model_map_tab, 2);
}

static bool initialized = false;

const char *check_model_init(void)
{
    if (!initialized)
    {
        initialized = true;
        jm_version_string = JSON_MODEL_VERSION;
        check_model_map_tab[0] = (jm_propmap_t) { "", json_model_1 };
        check_model_map_tab[1] = (jm_propmap_t) { "empty", json_model_2 };
        jm_sort_propmap(check_model_map_tab, 2);
    }
    return NULL;
}

void check_model_free(void)
{
    if (initialized)
        initialized = false;

        // cleanup code
}

/*
 * # API
 *
 * ```c
 * bool error;
 * char *message;
 *
 * bool valid = check(json_value, "model-name", &error, &message);
 *
 * if (message)
 *    free(message), message = NULL;
 * ```
 *
 * - `error` is set of there was an error during initialization or if the model does not exists.
 * - `message` is provided if a non NULL pointer is passed, and must be freed by the caller.
 */
bool
check_model(const json_t *val, const char *name, bool *error, char **reasons)
{
    return jm_generic_entry(check_model_init, check_model_map, val, name, error, reasons);
}
