// Typescript interface generated by JSON Model Compiler
// for ./ref-001
// see https://json-model.org/

export interface b {
	a: number
	b: number
	c: number
}
export interface a {
	a: number
	b: number
}

export interface RootModel {
}
