//
// Generated by JSON Model Compiler version 2
// see https://github.com/clairey-zx81/json-model
//
import 'dart:convert';
import 'dart:io';
import 'dart:core';
// Import the helper library generated nearby
import 'package:json_model_runtime/json_model.dart' as runtime;
import 'package:json_model_runtime/main.dart';

//
// Generated JSON Model Validator
//
const String JSON_MODEL_VERSION = "2";

var _jm_map_0 = Map();
var check_model_map = <String, Function>{};

// object .movie.'|'.0
bool _jm_obj_0(dynamic val, List<dynamic>? path, List<dynamic>? rep)
{
    // check close must only props
    if (! (val is Map))
    {
        rep?.add(["not an object [.movie.'|'.0]", path]);
        return false;
    }
    if (val.length != 2)
    {
        rep?.add(["bad property count [.movie.'|'.0]", path]);
        return false;
    }
    List<dynamic>? lpath;
    dynamic pval;
    bool res;
    if (! val.containsKey("t"))
    {
        rep?.add(["missing mandatory prop <t> [.movie.'|'.0]", path]);
        return false;
    }
    lpath = (path != null ? [...?path, "t"] : null);
    pval = val["t"];
    // .movie.'|'.0.t
    res = (pval is String) && pval.compareTo("fr") == 0;
    if (! res)
    {
        rep?.add(["unexpected fr [.movie.'|'.0.t]", (path != null ? lpath : null)]);
        rep?.add(["unexpected value for mandatory prop <t> [.movie.'|'.0]", (path != null ? lpath : null)]);
        return false;
    }
    if (! val.containsKey("titre"))
    {
        rep?.add(["missing mandatory prop <titre> [.movie.'|'.0]", path]);
        return false;
    }
    lpath = (path != null ? [...?path, "titre"] : null);
    pval = val["titre"];
    // .movie.'|'.0.titre
    res = (pval is String);
    if (! res)
    {
        rep?.add(["unexpected string [.movie.'|'.0.titre]", (path != null ? lpath : null)]);
        rep?.add(["unexpected value for mandatory prop <titre> [.movie.'|'.0]", (path != null ? lpath : null)]);
        return false;
    }
    return true;
}

// object .movie.'|'.1
bool _jm_obj_1(dynamic val, List<dynamic>? path, List<dynamic>? rep)
{
    // check close must only props
    if (! (val is Map))
    {
        rep?.add(["not an object [.movie.'|'.1]", path]);
        return false;
    }
    if (val.length != 2)
    {
        rep?.add(["bad property count [.movie.'|'.1]", path]);
        return false;
    }
    List<dynamic>? lpath;
    dynamic pval;
    bool res;
    if (! val.containsKey("t"))
    {
        rep?.add(["missing mandatory prop <t> [.movie.'|'.1]", path]);
        return false;
    }
    lpath = (path != null ? [...?path, "t"] : null);
    pval = val["t"];
    // .movie.'|'.1.t
    res = (pval is String) && pval.compareTo("en") == 0;
    if (! res)
    {
        rep?.add(["unexpected en [.movie.'|'.1.t]", (path != null ? lpath : null)]);
        rep?.add(["unexpected value for mandatory prop <t> [.movie.'|'.1]", (path != null ? lpath : null)]);
        return false;
    }
    if (! val.containsKey("title"))
    {
        rep?.add(["missing mandatory prop <title> [.movie.'|'.1]", path]);
        return false;
    }
    lpath = (path != null ? [...?path, "title"] : null);
    pval = val["title"];
    // .movie.'|'.1.title
    res = (pval is String);
    if (! res)
    {
        rep?.add(["unexpected string [.movie.'|'.1.title]", (path != null ? lpath : null)]);
        rep?.add(["unexpected value for mandatory prop <title> [.movie.'|'.1]", (path != null ? lpath : null)]);
        return false;
    }
    return true;
}

// object .movie.'|'.2
bool _jm_obj_2(dynamic val, List<dynamic>? path, List<dynamic>? rep)
{
    // check close must only props
    if (! (val is Map))
    {
        rep?.add(["not an object [.movie.'|'.2]", path]);
        return false;
    }
    if (val.length != 2)
    {
        rep?.add(["bad property count [.movie.'|'.2]", path]);
        return false;
    }
    List<dynamic>? lpath;
    dynamic pval;
    bool res;
    if (! val.containsKey("t"))
    {
        rep?.add(["missing mandatory prop <t> [.movie.'|'.2]", path]);
        return false;
    }
    lpath = (path != null ? [...?path, "t"] : null);
    pval = val["t"];
    // .movie.'|'.2.t
    res = (pval is String) && pval.compareTo("de") == 0;
    if (! res)
    {
        rep?.add(["unexpected de [.movie.'|'.2.t]", (path != null ? lpath : null)]);
        rep?.add(["unexpected value for mandatory prop <t> [.movie.'|'.2]", (path != null ? lpath : null)]);
        return false;
    }
    if (! val.containsKey("Title"))
    {
        rep?.add(["missing mandatory prop <Title> [.movie.'|'.2]", path]);
        return false;
    }
    lpath = (path != null ? [...?path, "Title"] : null);
    pval = val["Title"];
    // .movie.'|'.2.Title
    res = (pval is String);
    if (! res)
    {
        rep?.add(["unexpected string [.movie.'|'.2.Title]", (path != null ? lpath : null)]);
        rep?.add(["unexpected value for mandatory prop <Title> [.movie.'|'.2]", (path != null ? lpath : null)]);
        return false;
    }
    return true;
}

// object .movie.'|'.3
bool _jm_obj_3(dynamic val, List<dynamic>? path, List<dynamic>? rep)
{
    // check close must only props
    if (! (val is Map))
    {
        rep?.add(["not an object [.movie.'|'.3]", path]);
        return false;
    }
    if (val.length != 2)
    {
        rep?.add(["bad property count [.movie.'|'.3]", path]);
        return false;
    }
    List<dynamic>? lpath;
    dynamic pval;
    bool res;
    if (! val.containsKey("t"))
    {
        rep?.add(["missing mandatory prop <t> [.movie.'|'.3]", path]);
        return false;
    }
    lpath = (path != null ? [...?path, "t"] : null);
    pval = val["t"];
    // .movie.'|'.3.t
    res = (pval is String) && pval.compareTo("ru") == 0;
    if (! res)
    {
        rep?.add(["unexpected ru [.movie.'|'.3.t]", (path != null ? lpath : null)]);
        rep?.add(["unexpected value for mandatory prop <t> [.movie.'|'.3]", (path != null ? lpath : null)]);
        return false;
    }
    if (! val.containsKey("suti"))
    {
        rep?.add(["missing mandatory prop <suti> [.movie.'|'.3]", path]);
        return false;
    }
    lpath = (path != null ? [...?path, "suti"] : null);
    pval = val["suti"];
    // .movie.'|'.3.suti
    res = (pval is String);
    if (! res)
    {
        rep?.add(["unexpected string [.movie.'|'.3.suti]", (path != null ? lpath : null)]);
        rep?.add(["unexpected value for mandatory prop <suti> [.movie.'|'.3]", (path != null ? lpath : null)]);
        return false;
    }
    return true;
}


// check $ (.)
bool json_model_1(dynamic val, List<dynamic>? path, List<dynamic>? rep)
{
    // .
    // check close must only props
    if (! (val is Map))
    {
        rep?.add(["not an object [.]", path]);
        return false;
    }
    if (val.length != 1)
    {
        rep?.add(["bad property count [.]", path]);
        return false;
    }
    List<dynamic>? lpath;
    dynamic pval;
    bool res;
    if (! val.containsKey("movie"))
    {
        rep?.add(["missing mandatory prop <movie> [.]", path]);
        return false;
    }
    lpath = (path != null ? [...?path, "movie"] : null);
    pval = val["movie"];
    // .movie
    bool iso_0 = (pval is Map);
    res = iso_0;
    if (res)
    {
        if (pval.containsKey("t"))
        {
            dynamic tag_0 = pval["t"];
            dynamic fun_0 = _jm_map_0[tag_0];
            if (fun_0 != null)
            {
                res = fun_0(pval, (path != null ? lpath : null), rep);
            }
            else
            {
                res = false;
                rep?.add(["tag <t> value not found [.movie.'|']", (path != null ? lpath : null)]);
            }
        }
        else
        {
            res = false;
            rep?.add(["tag prop <t> is missing [.movie.'|']", (path != null ? lpath : null)]);
        }
    }
    else
    {
        rep?.add(["value is not an object [.movie.'|']", (path != null ? lpath : null)]);
    }
    if (! res)
    {
        rep?.add(["unexpected value for mandatory prop <movie> [.]", (path != null ? lpath : null)]);
        return false;
    }
    return true;
}


// dart_init.dart
class GlobalState {
  static bool initializer = false;
}

Function? check_model_fun(String name) {
  return check_model_map[name];
}


void check_model_init() {
  if (!GlobalState.initializer){
    GlobalState.initializer = true;
  }
        _jm_map_0["fr"] = _jm_obj_0;
        _jm_map_0["en"] = _jm_obj_1;
        _jm_map_0["de"] = _jm_obj_2;
        _jm_map_0["ru"] = _jm_obj_3;
        check_model_map[""] = json_model_1;
}

// dart_free.dart
void check_model_free() {
  GlobalState.initializer = true;
}


void main(List<String> args) {
  runValidation(
    args,
    check_model_init,
    check_model_fun,
    check_model_free,
  );
}
