//
// Generated by JSON Model Compiler version 2
// see https://github.com/clairey-zx81/json-model
//

import json_model.*;
import java.util.Map;
import java.util.Set;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.regex.Pattern;
import java.util.regex.Matcher;

@SuppressWarnings("unchecked")
public class orob_00 extends ModelChecker
{
    static public final String VERSION = "2";

    public Map<String, Checker> orob_00_map_pmap;

    // object .'|'.1
    public boolean _jm_obj_0(Object val, Path path, Report rep)
    {
        // check close must only props
        if (! json.isObject(val))
        {
            if (rep != null) rep.addEntry("not an object [.'|'.1]", path);
            return false;
        }
        if (json.objectSize(val) != 1)
        {
            if (rep != null) rep.addEntry("bad property count [.'|'.1]", path);
            return false;
        }
        Object pval;
        boolean res;
        if (! json.objectHasProp(val, "b"))
        {
            if (rep != null) rep.addEntry("missing mandatory prop <b> [.'|'.1]", path);
            return false;
        }
        pval = json.objectValue(val, "b");
        // .'|'.1.b
        res = json.isInteger(pval) && json.asLong(pval) >= 0;
        if (! res)
        {
            if (rep != null) rep.addEntry("not a 0 strict int [.'|'.1.b]", path);
            if (rep != null) rep.addEntry("unexpected value for mandatory prop <b> [.'|'.1]", path);
            return false;
        }
        return true;
    }

    // object .'|'.0
    public boolean _jm_obj_1(Object val, Path path, Report rep)
    {
        // check close must only props
        if (! json.isObject(val))
        {
            if (rep != null) rep.addEntry("not an object [.'|'.0]", path);
            return false;
        }
        if (json.objectSize(val) != 1)
        {
            if (rep != null) rep.addEntry("bad property count [.'|'.0]", path);
            return false;
        }
        Object pval;
        boolean res;
        if (! json.objectHasProp(val, "a"))
        {
            if (rep != null) rep.addEntry("missing mandatory prop <a> [.'|'.0]", path);
            return false;
        }
        pval = json.objectValue(val, "a");
        // .'|'.0.a
        res = json.isInteger(pval) && json.asLong(pval) >= 0;
        if (! res)
        {
            if (rep != null) rep.addEntry("not a 0 strict int [.'|'.0.a]", path);
            if (rep != null) rep.addEntry("unexpected value for mandatory prop <a> [.'|'.0]", path);
            return false;
        }
        return true;
    }

    // check $ (.)
    public boolean json_model_1(Object val, Path path, Report rep)
    {
        boolean res;
        // no discriminant or
        // .
        res = json.isObject(val);
        if (! res)
        {
            if (rep != null) rep.addEntry("unexpected type [.'|']", path);
        }
        if (res)
        {
            // .'|'.0
            res = _jm_obj_1(val, path, rep);
            if (! res)
            {
                if (rep != null) rep.addEntry("unexpected element [.'|'.0]", path);
            }
            if (! res)
            {
                // .'|'.1
                res = _jm_obj_0(val, path, rep);
                if (! res)
                {
                    if (rep != null) rep.addEntry("unexpected element [.'|'.1]", path);
                }
            }
            if (res)
            {
                if (rep != null) rep.clearEntries();
            }
            else
            {
                if (rep != null) rep.addEntry("no model matched [.'|']", path);
            }
        }
        return res;
    }


    public void init(JSON json)
    {
        if (!initialized)
        {
            try {
            orob_00_map_pmap = new HashMap<String, Checker>();
            orob_00_map_pmap.put("", new Checker() { public boolean call(Object o, Path p, Report r) { return json_model_1(o, p, r);} });
                super.init(json);
            }
            catch (Exception e) {
                throw new Error("cannot initialized model checker: " + e);
            }
        }
    }

    public void free()
    {
        if (initialized)
        {
            super.free();
            orob_00_map_pmap = null;
        }
    }

    public Checker get(String name)
    {
        return orob_00_map_pmap.get(name);
    }

    public Set<String> models()
    {
        return orob_00_map_pmap.keySet();
    }

    static public void main(String[] args) throws Exception
    {
        ModelChecker checker = new orob_00();
        Main.main("orob_00", checker, VERSION, args);
    }
}
