#! /usr/bin/perl -CDSA
#
# Generated by JSON Model Compiler version 2
# see https://github.com/clairey-zx81/json-model
#
use utf8;
use strict;
use warnings;
no warnings "uninitialized";
use re::engine::RE2;
use JSON::JsonModel;
use constant JMC_VERSION => "2";


sub json_model_4($$$);
sub json_model_3($$$);
sub json_model_1($$$);
sub json_model_5($$$);
my %check_model_map;

# check $root (.'$root')
sub json_model_4($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$root'
    my $res = json_model_5($val, $path, $rep);
    push @$rep, ["unexpected value for model \"\\\$Root\" [.'\$root']", $path] if defined $rep and not $res;
    return $res;
}

# check $Root (.'$Root')
sub json_model_3($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$Root'
    my $res = json_model_5($val, $path, $rep);
    push @$rep, ["unexpected value for model \"\\\$root#Root\" [.'\$Root']", $path] if defined $rep and not $res;
    return $res;
}

# check $ (.)
sub json_model_1($$$)
{
    my ($val, $path, $rep) = @_;
    # .
    my $res = json_model_5($val, $path, $rep);
    push @$rep, ["unexpected value for model \"\\\$Root\" [.]", $path] if defined $rep and not $res;
    return $res;
}

# check $root#Root (.'$root#Root')
sub json_model_5($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$root#Root'
    # check close must only props
    unless (jm_is_object($val))
    {
        push @$rep, ["not an object [.'\$root#Root']", $path] if defined $rep;
        return 0;
    }
    if (jm_obj_size($val) != 2)
    {
        push @$rep, ["bad property count [.'\$root#Root']", $path] if defined $rep;
        return 0;
    }
    my $lpath;
    my $pval;
    unless (exists $$val{"id"})
    {
        push @$rep, ["missing mandatory prop <id> [.'\$root#Root']", $path] if defined $rep;
        return 0;
    }
    $lpath = defined $path ? [@{$path}, "id"] : undef;
    $pval = $$val{"id"};
    # .'$root#Root'.id
    my $res = jm_is_integer($pval) && $pval == 1;
    unless ($res)
    {
        push @$rep, ["unexpected value for model \"=1\" [.'\$root#Root'.id]", defined $path ? $lpath : undef] if defined $rep;
        push @$rep, ["unexpected value for mandatory prop <id> [.'\$root#Root']", defined $path ? $lpath : undef] if defined $rep;
        return 0;
    }
    unless (exists $$val{"name"})
    {
        push @$rep, ["missing mandatory prop <name> [.'\$root#Root']", $path] if defined $rep;
        return 0;
    }
    $lpath = defined $path ? [@{$path}, "name"] : undef;
    $pval = $$val{"name"};
    # .'$root#Root'.name
    $res = jm_is_string($pval);
    unless ($res)
    {
        push @$rep, ["unexpected value for model \"\" [.'\$root#Root'.name]", defined $path ? $lpath : undef] if defined $rep;
        push @$rep, ["unexpected value for mandatory prop <name> [.'\$root#Root']", defined $path ? $lpath : undef] if defined $rep;
        return 0;
    }
    return 1;
}


# initialization of global variables

our $initialized = 0;

sub check_model_init()
{
    if (!$initialized)
    {
        $initialized = 1;
        %check_model_map = (
            "" => \&json_model_5,
            "root" => \&json_model_5,
            "Root" => \&json_model_5,
        );
    }
}

sub check_model_free()
{
    if ($initialized)
    {
        $initialized = 0;
        %check_model_map = ();
    }
}

sub check_model_mapper($)
{
    my ($name) = @_;
    die "unexpected model name \"$name\"" unless exists $check_model_map{$name};
    return $check_model_map{$name};
}

sub check_model($$$)
{
    my ($json, $name, $rep) = @_;
    die "unexpected model name \"$name\"" unless exists $check_model_map{$name};
    my $path = defined $rep ? [] : undef;
    return $check_model_map{$name}($json, $path, $rep);
}

#
# SCRIPT EXECUTION
#
check_model_init();
jm_main(\&check_model, \%check_model_map, JMC_VERSION);
check_model_free();
