// Typescript interface generated by JSON Model Compiler
// for ./disc
// see https://json-model.org/


export interface RootModel_0 {
	d: 0
	a: string
}

export interface RootModel_1 {
	d: 1
	a: number
}

export interface RootModel_2 {
	d: 2
	a: null
}

export interface RootModel_3 {
	d: 3
	a: boolean
}

export type RootModel = (RootModel_0 | RootModel_1 | RootModel_2 | RootModel_3)
