// Typescript interface generated by JSON Model Compiler
// for ./am2_00
// see https://json-model.org/


export interface RootModel_3 {
	"": any
}

export type RootModel = (null | any[] | string | RootModel_3)
