#! /bin/env python
#
# Generated by JSON Model Compiler version 2
# see https://github.com/clairey-zx81/json-model
#
import math
from typing import Callable
import re2 as re
from json_model.runtime import *
__version__ = "2"

def check_model_fun(name: str) -> CheckFun:
    """Return check function for JSON model name."""
    return check_model_map[name]

# entry point for generated checkers
def check_model(val: Jsonable, name: str = "", rep: Report = None) -> bool:
    """Check val validity against JSON Model name."""
    if name not in check_model_map:
        raise Exception(f"unexpected model name: {name}")
    checker = check_model_map[name]
    return checker(val, [], rep)

check_model_map: PropMap

# check $Obj (.'$Obj')
def json_model_2(val: Jsonable, path: Path, rep: Report) -> bool:
    # .'$Obj'
    if not isinstance(val, dict):
        rep is None or rep.append(("not an object [.'$Obj']", path))
        return False
    res: bool
    must_count: int = 0
    for prop, pval in val.items():
        lpath_0: Path = (path + [ prop ]) if path is not None else None
        if prop == "a":
            # handle must a property
            must_count += 1
            # .'$Obj'.a
            res = isinstance(pval, str)
            if not res:
                rep is None or rep.append(("unexpected value for model \"\" [.'$Obj'.a]", lpath_0 if path is not None else None))
                rep is None or rep.append(("invalid mandatory prop value [.'$Obj'.a]", lpath_0 if path is not None else None))
                return False
            continue
        if prop == "b":
            # handle may b property
            # .'$Obj'.b
            res = isinstance(pval, str)
            if not res:
                rep is None or rep.append(("unexpected value for model \"\" [.'$Obj'.b]", lpath_0 if path is not None else None))
                rep is None or rep.append(("invalid optional prop value [.'$Obj'.b]", lpath_0 if path is not None else None))
                return False
            continue
        rep is None or rep.append(("unexpected prop [.'$Obj']", lpath_0 if path is not None else None))
        return False
    if must_count != 1:
        if rep is not None:
            if not "a" in val:
                rep is None or rep.append(("missing mandatory prop <a> [.'$Obj']", path))
        return False
    return True

# check $ (.)
def json_model_1(val: Jsonable, path: Path, rep: Report) -> bool:
    # with a reference
    # .
    res: bool = isinstance(val, dict)
    if res:
        # .'|'.6
        res = json_model_2(val, path, rep)
        if not res:
            rep is None or rep.append(("unexpected value for model \"$Obj\" [.'|'.6]", path))
    else:
        res = True
    return res


# initialization guard
initialized: bool = False

# differed module initializations
def check_model_init():
    global initialized
    if not initialized:
        initialized = True
        global check_model_map
        check_model_map = {
            "": json_model_1,
            "Obj": json_model_2,
        }

# differed module cleanup
def check_model_free():
    global initialized
    if initialized:
        initialized = False

if __name__ == "__main__":
    check_model_init()
    main(check_model_fun, check_model_map, __version__)
    check_model_free()
