.PHONY: clean
clean:
	$(RM) person.out person.c person.o \
	    person.js person.mjs \
	    person.py Person.py PersonModels.py \
	    person.sql \
	    person.schema.json \
	    person.pl person.pm \
	    Person.java *.class
	$(RM) -r venv
