//
// Generated by JSON Model Compiler version 2.0b0
// see https://github.com/clairey-zx81/json-model
//

// regular expression engine
#define PCRE2_CODE_UNIT_WIDTH 8
#include <pcre2.h>

#include <json-model.h>
#define JSON_MODEL_VERSION "2.0b0"

static bool json_model_2(const json_t *val, jm_path_t *path, jm_report_t *rep);
static bool _jm_f_0(const json_t *val, jm_path_t *path, jm_report_t *rep);
static bool _jm_f_1(const json_t *val, jm_path_t *path, jm_report_t *rep);
static bool _jm_f_2(const json_t *val, jm_path_t *path, jm_report_t *rep);
static bool _jm_f_3(const json_t *val, jm_path_t *path, jm_report_t *rep);
static jm_propmap_t _jm_obj_0_mup_tab[4];
static bool json_model_5(const json_t *val, jm_path_t *path, jm_report_t *rep);
static bool json_model_4(const json_t *val, jm_path_t *path, jm_report_t *rep);
static bool _jm_f_4(const json_t *val, jm_path_t *path, jm_report_t *rep);
static bool _jm_f_5(const json_t *val, jm_path_t *path, jm_report_t *rep);
static bool _jm_f_6(const json_t *val, jm_path_t *path, jm_report_t *rep);
static bool _jm_f_7(const json_t *val, jm_path_t *path, jm_report_t *rep);
static bool _jm_f_8(const json_t *val, jm_path_t *path, jm_report_t *rep);
static bool _jm_f_9(const json_t *val, jm_path_t *path, jm_report_t *rep);
static jm_propmap_t _jm_obj_2_mup_tab[6];
static bool json_model_1(const json_t *val, jm_path_t *path, jm_report_t *rep);
jm_propmap_t check_model_map_tab[4];
const size_t check_model_map_size = 4;

// check $T (.'$T')
static bool json_model_2(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .'$T'
    res = json_is_string(val) && strcmp(json_string_value(val), "cst_02") == 0;
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected _cst_02 [.'$T']", path);
    }
    return res;
}

// check _jm_obj_0_mup_a (.'$R'.a)
static bool _jm_f_0(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .'$R'.a
    res = json_is_string(val) && strcmp(json_string_value(val), "cst_01") == 0;
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected _cst_01 [.'$R'.a]", path);
    }
    return res;
}

// check _jm_obj_0_mup_b (.'$R'.b)
static bool _jm_f_1(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .'$R'.b
    res = json_is_string(val) && strcmp(json_string_value(val), "cst_01") == 0;
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected _cst_01 [.'$R'.b]", path);
    }
    return res;
}

// check _jm_obj_0_mup_c (.'$R'.c)
static bool _jm_f_2(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .'$R'.c
    res = json_is_string(val) && strcmp(json_string_value(val), "cst_01") == 0;
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected _cst_01 [.'$R'.c]", path);
    }
    return res;
}

// check _jm_obj_0_mup_d (.'$R'.d)
static bool _jm_f_3(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .'$R'.d
    res = json_is_string(val) && strcmp(json_string_value(val), "cst_01") == 0;
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected _cst_01 [.'$R'.d]", path);
    }
    return res;
}

static jm_check_fun_t _jm_obj_0_mup(const char *pname)
{
    return jm_search_propmap(pname, _jm_obj_0_mup_tab, 4);
}

// object .'$R'
static bool _jm_obj_0(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    if (! json_is_object(val))
    {
        if (rep) jm_report_add_entry(rep, "not an object [.'$R']", path);
        return false;
    }
    jm_check_fun_t pfun;
    int64_t must_count = 0;
    const char *prop;
    json_t *pval;
    json_object_foreach((json_t *) val, prop, pval)
    {
        jm_path_t lpath_0 = (jm_path_t) { prop, 0, path, NULL };
        if ((pfun = _jm_obj_0_mup(prop)))
        {
            // handle 4 mandatory props
            if (pfun != NULL)
            {
                must_count += 1;
                if (! pfun(pval, (path ? &lpath_0 : NULL), rep))
                {
                    if (rep) jm_report_add_entry(rep, "invalid mandatory prop value [.'$R']", (path ? &lpath_0 : NULL));
                    return false;
                }
            }
        }
        else
        {
            if (rep) jm_report_add_entry(rep, "unexpected prop [.'$R']", (path ? &lpath_0 : NULL));
            return false;
        }
    }
    if (must_count != 4)
    {
        if (rep != NULL)
        {
            if (! (json_object_get(val, "a") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <a> [.'$R']", path);
            }
            if (! (json_object_get(val, "b") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <b> [.'$R']", path);
            }
            if (! (json_object_get(val, "c") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <c> [.'$R']", path);
            }
            if (! (json_object_get(val, "d") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <d> [.'$R']", path);
            }
        }
        return false;
    }
    return true;
}

// check $R (.'$R')
static bool json_model_5(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .'$R'
    res = _jm_obj_0(val, path, rep);
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected object [.'$R']", path);
    }
    return res;
}

// object .'$Z'
static bool _jm_obj_1(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    if (! json_is_object(val))
    {
        if (rep) jm_report_add_entry(rep, "not an object [.'$Z']", path);
        return false;
    }
    bool res;
    int64_t must_count = 0;
    const char *prop;
    json_t *pval;
    json_object_foreach((json_t *) val, prop, pval)
    {
        jm_path_t lpath_1 = (jm_path_t) { prop, 0, path, NULL };
        if (strcmp(prop, "e") == 0)
        {
            // handle must e property
            must_count += 1;
            // .'$Z'.e
            res = json_is_string(pval) && strcmp(json_string_value(pval), "cst_02") == 0;
            if (! res)
            {
                if (rep) jm_report_add_entry(rep, "unexpected _cst_02 [.'$Z'.e]", (path ? &lpath_1 : NULL));
            }
            if (! res)
            {
                if (rep) jm_report_add_entry(rep, "invalid mandatory prop value [.'$Z'.e]", (path ? &lpath_1 : NULL));
                return false;
            }
        }
        else if (strcmp(prop, "f") == 0)
        {
            // handle must f property
            must_count += 1;
            // .'$Z'.f
            res = json_is_string(pval) && strcmp(json_string_value(pval), "cst_02") == 0;
            if (! res)
            {
                if (rep) jm_report_add_entry(rep, "unexpected _cst_02 [.'$Z'.f]", (path ? &lpath_1 : NULL));
            }
            if (! res)
            {
                if (rep) jm_report_add_entry(rep, "invalid mandatory prop value [.'$Z'.f]", (path ? &lpath_1 : NULL));
                return false;
            }
        }
        else
        {
            if (rep) jm_report_add_entry(rep, "unexpected prop [.'$Z']", (path ? &lpath_1 : NULL));
            return false;
        }
    }
    if (must_count != 2)
    {
        if (rep != NULL)
        {
            if (! (json_object_get(val, "e") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <e> [.'$Z']", path);
            }
            if (! (json_object_get(val, "f") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <f> [.'$Z']", path);
            }
        }
        return false;
    }
    return true;
}

// check $Z (.'$Z')
static bool json_model_4(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .'$Z'
    res = _jm_obj_1(val, path, rep);
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected object [.'$Z']", path);
    }
    return res;
}

// check _jm_obj_2_mup_a (.a)
static bool _jm_f_4(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .a
    res = json_is_string(val) && strcmp(json_string_value(val), "cst_01") == 0;
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected _cst_01 [.a]", path);
    }
    return res;
}

// check _jm_obj_2_mup_b (.b)
static bool _jm_f_5(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .b
    res = json_is_string(val) && strcmp(json_string_value(val), "cst_01") == 0;
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected _cst_01 [.b]", path);
    }
    return res;
}

// check _jm_obj_2_mup_c (.c)
static bool _jm_f_6(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .c
    res = json_is_string(val) && strcmp(json_string_value(val), "cst_01") == 0;
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected _cst_01 [.c]", path);
    }
    return res;
}

// check _jm_obj_2_mup_d (.d)
static bool _jm_f_7(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .d
    res = json_is_string(val) && strcmp(json_string_value(val), "cst_01") == 0;
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected _cst_01 [.d]", path);
    }
    return res;
}

// check _jm_obj_2_mup_e (.e)
static bool _jm_f_8(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .e
    res = json_is_string(val) && strcmp(json_string_value(val), "cst_02") == 0;
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected _cst_02 [.e]", path);
    }
    return res;
}

// check _jm_obj_2_mup_f (.f)
static bool _jm_f_9(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .f
    res = json_is_string(val) && strcmp(json_string_value(val), "cst_02") == 0;
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected _cst_02 [.f]", path);
    }
    return res;
}

static jm_check_fun_t _jm_obj_2_mup(const char *pname)
{
    return jm_search_propmap(pname, _jm_obj_2_mup_tab, 6);
}

// object .
static bool _jm_obj_2(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    if (! json_is_object(val))
    {
        if (rep) jm_report_add_entry(rep, "not an object [.]", path);
        return false;
    }
    jm_check_fun_t pfun;
    int64_t must_count = 0;
    const char *prop;
    json_t *pval;
    json_object_foreach((json_t *) val, prop, pval)
    {
        jm_path_t lpath_2 = (jm_path_t) { prop, 0, path, NULL };
        if ((pfun = _jm_obj_2_mup(prop)))
        {
            // handle 6 mandatory props
            if (pfun != NULL)
            {
                must_count += 1;
                if (! pfun(pval, (path ? &lpath_2 : NULL), rep))
                {
                    if (rep) jm_report_add_entry(rep, "invalid mandatory prop value [.]", (path ? &lpath_2 : NULL));
                    return false;
                }
            }
        }
        else
        {
            if (rep) jm_report_add_entry(rep, "unexpected prop [.]", (path ? &lpath_2 : NULL));
            return false;
        }
    }
    if (must_count != 6)
    {
        if (rep != NULL)
        {
            if (! (json_object_get(val, "a") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <a> [.]", path);
            }
            if (! (json_object_get(val, "b") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <b> [.]", path);
            }
            if (! (json_object_get(val, "c") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <c> [.]", path);
            }
            if (! (json_object_get(val, "d") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <d> [.]", path);
            }
            if (! (json_object_get(val, "e") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <e> [.]", path);
            }
            if (! (json_object_get(val, "f") != NULL))
            {
                if (rep) jm_report_add_entry(rep, "missing mandatory prop <f> [.]", path);
            }
        }
        return false;
    }
    return true;
}

// check $ (.)
static bool json_model_1(const json_t *val, jm_path_t *path, jm_report_t *rep)
{
    bool res;
    // .
    res = _jm_obj_2(val, path, rep);
    if (! res)
    {
        if (rep) jm_report_add_entry(rep, "unexpected object [.]", path);
    }
    return res;
}

jm_check_fun_t check_model_map(const char *pname)
{
    return jm_search_propmap(pname, check_model_map_tab, 4);
}

static bool initialized = false;

const char *check_model_init(void)
{
    if (!initialized)
    {
        initialized = true;
        jm_version_string = JSON_MODEL_VERSION;
        _jm_obj_0_mup_tab[0] = (jm_propmap_t) { "a", _jm_f_0 };
        _jm_obj_0_mup_tab[1] = (jm_propmap_t) { "b", _jm_f_1 };
        _jm_obj_0_mup_tab[2] = (jm_propmap_t) { "c", _jm_f_2 };
        _jm_obj_0_mup_tab[3] = (jm_propmap_t) { "d", _jm_f_3 };
        jm_sort_propmap(_jm_obj_0_mup_tab, 4);
        _jm_obj_2_mup_tab[0] = (jm_propmap_t) { "a", _jm_f_4 };
        _jm_obj_2_mup_tab[1] = (jm_propmap_t) { "b", _jm_f_5 };
        _jm_obj_2_mup_tab[2] = (jm_propmap_t) { "c", _jm_f_6 };
        _jm_obj_2_mup_tab[3] = (jm_propmap_t) { "d", _jm_f_7 };
        _jm_obj_2_mup_tab[4] = (jm_propmap_t) { "e", _jm_f_8 };
        _jm_obj_2_mup_tab[5] = (jm_propmap_t) { "f", _jm_f_9 };
        jm_sort_propmap(_jm_obj_2_mup_tab, 6);
        check_model_map_tab[0] = (jm_propmap_t) { "", json_model_1 };
        check_model_map_tab[1] = (jm_propmap_t) { "T", json_model_2 };
        check_model_map_tab[2] = (jm_propmap_t) { "R", json_model_5 };
        check_model_map_tab[3] = (jm_propmap_t) { "Z", json_model_4 };
        jm_sort_propmap(check_model_map_tab, 4);
    }
    return NULL;
}

void check_model_free(void)
{
    if (initialized)
    {
        initialized = false;

        // cleanup code
    }
}


/*
 * # API
 *
 * ```c
 * bool error;
 * char *message;
 *
 * bool valid = check(json_value, "model-name", &error, &message);
 *
 * if (message)
 *    free(message), message = NULL;
 * ```
 *
 * - `error` is set of there was an error during initialization or if the model does not exists.
 * - `message` is provided if a non NULL pointer is passed, and must be freed by the caller.
 */
bool
check_model(const json_t *val, const char *name, bool *error, char **reasons)
{
    return jm_generic_entry(check_model_init, check_model_map, val, name, error, reasons);
}
