#! /bin/bash
#
# run jsonschema command in docker
#
# 2025-09-01: latest=v11.6.0

docker_image="ghcr.io/sourcemeta/jsonschema:latest"
docker_root="docker run --name blaze_cli_$$ -v .:/workspace --rm"
docker_user="$docker_root --user $(id -u):$(id -g)"

if [ "$#" -ge 1 -a "$1" = "help" ] ; then
  echo "$0 [ help | run | shell | root ] …"
elif [ "$#" -ge 1 -a "$1" = "shell" ] ; then
  shift 1
  exec $docker_user -i --entrypoint /bin/bash $docker_image "$@"
elif [ "$#" -ge 1 -a "$1" = "root" ] ; then
  shift 1
  exec $docker_root -i --entrypoint /bin/bash $docker_image "$@"
elif [ "$#" -ge 1 -a "$1" = "run" ] ; then
  shift 1
  exec $docker_user $docker_image "$@"
else
  exec $docker_user $docker_image "$@"
fi
