#! /usr/bin/perl
#
# Generated by JSON Model Compiler version 2
# see https://github.com/clairey-zx81/json-model
#
use strict;
use warnings;
no warnings "uninitialized";
use re::engine::RE2;
use JSON::JsonModel;
use constant JMC_VERSION => '2';


my %_jm_cst_0;
sub json_model_2($$$);
sub json_model_3($$$);
sub _jm_f_0($$$);
sub _jm_f_1($$$);
sub _jm_f_2($$$);
sub _jm_f_3($$$);
sub _jm_f_4($$$);
sub _jm_f_5($$$);
sub _jm_f_6($$$);
sub _jm_f_7($$$);
sub _jm_f_8($$$);
sub _jm_f_9($$$);
sub _jm_f_10($$$);
sub _jm_f_11($$$);
sub _jm_f_12($$$);
sub _jm_f_13($$$);
sub _jm_f_14($$$);
sub _jm_f_15($$$);
sub _jm_f_16($$$);
sub _jm_f_17($$$);
sub _jm_f_18($$$);
sub _jm_f_19($$$);
sub _jm_f_20($$$);
sub _jm_f_21($$$);
sub _jm_f_22($$$);
sub _jm_f_23($$$);
sub _jm_f_24($$$);
sub _jm_f_25($$$);
sub _jm_f_26($$$);
my %json_model_1_map;
sub json_model_1($$$);
my %check_model_map;


# check $allTypes (.'$allTypes')
sub json_model_2($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$allTypes'
    return jm_is_string($val) && exists $_jm_cst_0{$val};
}

# check $distinctStringArray (.'$distinctStringArray')
sub json_model_3($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$distinctStringArray'
    # .'$distinctStringArray'.'@'
    my $res = jm_is_array($val);
    if ($res)
    {
        for my $arr_0_idx (0 .. $#$val)
        {
            my $arr_0_item = $$val[$arr_0_idx];
            # .'$distinctStringArray'.'@'.0
            $res = jm_is_string($arr_0_item);
            if (! $res)
            {
                last;
            }
        }
    }
    if ($res)
    {
        $res = jm_is_unique_array($val, undef, undef);
    }
    return $res;
}

# check json_model_1_map_$schema (.'$schema')
sub _jm_f_0($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$schema'
    return jm_is_string($val);
}

# check json_model_1_map_additionalProperties (.additionalProperties)
sub _jm_f_1($$$)
{
    my ($val, $path, $rep) = @_;
    # .additionalProperties
    # .additionalProperties.'|'.0
    # .additionalProperties.'|'.1
    return jm_is_boolean($val) || json_model_1($val, undef, undef);
}

# check json_model_1_map_contentEncoding (.contentEncoding)
sub _jm_f_2($$$)
{
    my ($val, $path, $rep) = @_;
    # .contentEncoding
    return jm_is_string($val);
}

# check json_model_1_map_default (.default)
sub _jm_f_3($$$)
{
    my ($val, $path, $rep) = @_;
    # .default
    return 1;
}

# check json_model_1_map_description (.description)
sub _jm_f_4($$$)
{
    my ($val, $path, $rep) = @_;
    # .description
    return jm_is_string($val);
}

# check json_model_1_map_disallow (.disallow)
sub _jm_f_5($$$)
{
    my ($val, $path, $rep) = @_;
    # .disallow
    # .disallow.'|'.0
    # .disallow.'|'.1
    return jm_is_string($val) || json_model_3($val, undef, undef);
}

# check json_model_1_map_divisibleBy (.divisibleBy)
sub _jm_f_6($$$)
{
    my ($val, $path, $rep) = @_;
    # .divisibleBy
    return jm_is_numeric($val) && $val > 0.0;
}

# check json_model_1_map_enum (.enum)
sub _jm_f_7($$$)
{
    my ($val, $path, $rep) = @_;
    # .enum
    # .enum.'@'
    my $res = jm_is_array($val);
    if ($res)
    {
        # accept any array
        ;
        my $ival_0 = scalar @$val;
        $res = jm_is_unique_array($val, undef, undef) && $ival_0 >= 1;
    }
    return $res;
}

# check json_model_1_map_extends (.extends)
sub _jm_f_8($$$)
{
    my ($val, $path, $rep) = @_;
    # .extends
    # .extends.'|'.0
    my $res = json_model_1($val, undef, undef);
    if (! $res)
    {
        # .extends.'|'.1
        $res = jm_is_array($val);
        if ($res)
        {
            for my $arr_1_idx (0 .. $#$val)
            {
                my $arr_1_item = $$val[$arr_1_idx];
                # .extends.'|'.1.0
                $res = json_model_1($arr_1_item, undef, undef);
                if (! $res)
                {
                    last;
                }
            }
        }
    }
    return $res;
}

# check json_model_1_map_format (.format)
sub _jm_f_9($$$)
{
    my ($val, $path, $rep) = @_;
    # .format
    return jm_is_string($val);
}

# check json_model_1_map_id (.id)
sub _jm_f_10($$$)
{
    my ($val, $path, $rep) = @_;
    # .id
    return jm_is_string($val);
}

# check json_model_1_map_items (.items)
sub _jm_f_11($$$)
{
    my ($val, $path, $rep) = @_;
    # .items
    # .items.'|'.0
    my $res = json_model_1($val, undef, undef);
    if (! $res)
    {
        # .items.'|'.1
        $res = jm_is_array($val);
        if ($res)
        {
            for my $arr_2_idx (0 .. $#$val)
            {
                my $arr_2_item = $$val[$arr_2_idx];
                # .items.'|'.1.0
                $res = json_model_1($arr_2_item, undef, undef);
                if (! $res)
                {
                    last;
                }
            }
        }
    }
    return $res;
}

# check json_model_1_map_maxItems (.maxItems)
sub _jm_f_12($$$)
{
    my ($val, $path, $rep) = @_;
    # .maxItems
    return jm_is_integer($val) && $val >= 0;
}

# check json_model_1_map_maxLength (.maxLength)
sub _jm_f_13($$$)
{
    my ($val, $path, $rep) = @_;
    # .maxLength
    return jm_is_integer($val) && $val >= 0;
}

# check json_model_1_map_maximum (.maximum)
sub _jm_f_14($$$)
{
    my ($val, $path, $rep) = @_;
    # .maximum
    return jm_is_numeric($val);
}

# check json_model_1_map_maximumCanEqual (.maximumCanEqual)
sub _jm_f_15($$$)
{
    my ($val, $path, $rep) = @_;
    # .maximumCanEqual
    return jm_is_boolean($val);
}

# check json_model_1_map_minItems (.minItems)
sub _jm_f_16($$$)
{
    my ($val, $path, $rep) = @_;
    # .minItems
    return jm_is_integer($val) && $val >= 0;
}

# check json_model_1_map_minLength (.minLength)
sub _jm_f_17($$$)
{
    my ($val, $path, $rep) = @_;
    # .minLength
    return jm_is_integer($val) && $val >= 0;
}

# check json_model_1_map_minimum (.minimum)
sub _jm_f_18($$$)
{
    my ($val, $path, $rep) = @_;
    # .minimum
    return jm_is_numeric($val);
}

# check json_model_1_map_minimumCanEqual (.minimumCanEqual)
sub _jm_f_19($$$)
{
    my ($val, $path, $rep) = @_;
    # .minimumCanEqual
    return jm_is_boolean($val);
}

# check json_model_1_map_optional (.optional)
sub _jm_f_20($$$)
{
    my ($val, $path, $rep) = @_;
    # .optional
    return jm_is_boolean($val);
}

# check json_model_1_map_pattern (.pattern)
sub _jm_f_21($$$)
{
    my ($val, $path, $rep) = @_;
    # .pattern
    return jm_is_string($val) && jm_is_valid_regex($val, undef, undef);
}

# check json_model_1_map_properties (.properties)
sub _jm_f_22($$$)
{
    my ($val, $path, $rep) = @_;
    # .properties
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        # handle other props
        # .properties.''
        $res = json_model_1($pval, undef, undef);
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}

# check json_model_1_map_requires (.requires)
sub _jm_f_23($$$)
{
    my ($val, $path, $rep) = @_;
    # .requires
    # .requires.'|'.0
    # .requires.'|'.1
    return jm_is_string($val) || json_model_1($val, undef, undef);
}

# check json_model_1_map_title (.title)
sub _jm_f_24($$$)
{
    my ($val, $path, $rep) = @_;
    # .title
    return jm_is_string($val);
}

# check json_model_1_map_type (.type)
sub _jm_f_25($$$)
{
    my ($val, $path, $rep) = @_;
    # .type
    # .type.'|'.0
    my $res = json_model_2($val, undef, undef);
    if (! $res)
    {
        # .type.'|'.1
        $res = jm_is_array($val);
        if ($res)
        {
            for my $arr_3_idx (0 .. $#$val)
            {
                my $arr_3_item = $$val[$arr_3_idx];
                # .type.'|'.1.0
                # .type.'|'.1.0.'|'.0
                # .type.'|'.1.0.'|'.1
                $res = jm_is_string($arr_3_item) || json_model_1($arr_3_item, undef, undef);
                if (! $res)
                {
                    last;
                }
            }
        }
    }
    return $res;
}

# check json_model_1_map_uniqueItems (.uniqueItems)
sub _jm_f_26($$$)
{
    my ($val, $path, $rep) = @_;
    # .uniqueItems
    return jm_is_boolean($val);
}


# check $ (.)
sub json_model_1($$$)
{
    my ($val, $path, $rep) = @_;
    # JSON Model for JSON Schema Draft 02 [JSON_MODEL_STRICT_INT, JSON_MODEL_LOOSE_FLOAT]
    # .
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pfun;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if (($pfun = $json_model_1_map{$prop}))
        {
            # handle 27 may props
            if (defined($pfun) && ! &$pfun($pval, undef, undef))
            {
                return 0;
            }
            next;
        }
        return 0;
    }
    return 1;
}


# initialization of global variables

our $initialized = 0;

sub check_model_init()
{
    if (!$initialized)
    {
        $initialized = 1;
        %_jm_cst_0 = (
            'null' => 1,
            'boolean' => 1,
            'integer' => 1,
            'number' => 1,
            'string' => 1,
            'array' => 1,
            'object' => 1,
            'any' => 1,
        );
        %json_model_1_map = (
            '$schema' => \&_jm_f_0,
            'additionalProperties' => \&_jm_f_1,
            'contentEncoding' => \&_jm_f_2,
            'default' => \&_jm_f_3,
            'description' => \&_jm_f_4,
            'disallow' => \&_jm_f_5,
            'divisibleBy' => \&_jm_f_6,
            'enum' => \&_jm_f_7,
            'extends' => \&_jm_f_8,
            'format' => \&_jm_f_9,
            'id' => \&_jm_f_10,
            'items' => \&_jm_f_11,
            'maxItems' => \&_jm_f_12,
            'maxLength' => \&_jm_f_13,
            'maximum' => \&_jm_f_14,
            'maximumCanEqual' => \&_jm_f_15,
            'minItems' => \&_jm_f_16,
            'minLength' => \&_jm_f_17,
            'minimum' => \&_jm_f_18,
            'minimumCanEqual' => \&_jm_f_19,
            'optional' => \&_jm_f_20,
            'pattern' => \&_jm_f_21,
            'properties' => \&_jm_f_22,
            'requires' => \&_jm_f_23,
            'title' => \&_jm_f_24,
            'type' => \&_jm_f_25,
            'uniqueItems' => \&_jm_f_26,
        );
        %check_model_map = (
            '' => \&json_model_1,
            'allTypes' => \&json_model_2,
            'distinctStringArray' => \&json_model_3,
            'Schema' => \&json_model_1,
        );
    }
}

sub check_model_free()
{
    if ($initialized)
    {
        $initialized = 0;
        %_jm_cst_0 = ();
        %json_model_1_map = ();
        %check_model_map = ();
    }
}

sub check_model($$$)
{
    my ($json, $name, $rep) = @_;
    die "unexpected model name \"$name\"" unless exists $check_model_map{$name};
    my $path = defined $rep ? [] : undef;
    return $check_model_map{$name}($json, $path, $rep);
}

#
# SCRIPT EXECUTION
#
check_model_init();
jm_main(\&check_model, \%check_model_map, JMC_VERSION);
check_model_free();
