#! /bin/bash
#
# run jmc command in docker
#

docker="docker run --name awesome_jmc --user $UID:$GID -v .:/app/workspace --rm -it"

if [ "$#" -eq 1 -a "$1" = "shell" ] ; then
  exec $docker --entrypoint /bin/bash zx80/jmc
else
  exec $docker zx80/jmc "$@"
fi
