#! /bin/bash
#
# run jmc command in docker, with some extensions
#
# env:
# - JMC: jmc docker tag to run
# - JMC_ENV: names of environment variables to export
# - WORKDIR: working directory to use

docker_image="zx80/jmc:${JMC:-latest}"
docker_root=(docker run --name acme_jmc_$$ -v "${WORKDIR:-.}:/app/workspace" --rm)

# export environment variables to docker
for var in $JMC_ENV ; do
  if [ "${!var}" ] ; then
    docker_root+=(-e "$var=${!var}")
  else
    echo "### skipping empty or non existing environment variable $var" >&2
  fi
done

docker_user=("${docker_root[@]}")
docker_user+=(--user "$(id -u):$(id -g)")

if [ -f /etc/passwd ] ; then
  docker_user+=(-v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro)
fi

if [ "$#" -ge 1 -a "$1" = "help" ] ; then
  echo "$0 [ help | run | exec | shell | root ] …"
elif [ "$#" -ge 1 -a "$1" = "shell" ] ; then
  shift 1
  exec "${docker_user[@]}" -it --entrypoint /bin/bash "$docker_image" "$@"
elif [ "$#" -ge 1 -a "$1" = "root" ] ; then
  shift 1
  exec "${docker_root[@]}" -it --entrypoint /bin/bash "$docker_image" "$@"
elif [ "$#" -ge 1 -a "$1" = "exec" ] ; then
  exe=$2
  shift 2
  exec "${docker_user[@]}" --entrypoint "$exe" "$docker_image" "$@"
elif [ "$#" -ge 1 -a "$1" = "run" ] ; then
  shift 1
  exec "${docker_user[@]}" "$docker_image" "$@"
else
  exec "${docker_user[@]}" "$docker_image" "$@"
fi
