// Typescript interface generated by JSON Model Compiler
// for ./test-schema
// see https://json-model.org/

export interface TestCase {
	description: string
	comment?: string
	schema: any
	tests: Test[]
	specification?: Specification[]
}
export interface Specification {
	core?: Version
	validation?: Version
	ecma262?: Version
	perl5?: string
	quote?: string
	"/^rfc\\d+$/": Version
	"/^iso\\d+$/": Version
}
export interface Test {
	"#": string
	description: string
	comment?: string
	data: any
	valid: boolean
}
export type Version = string

export type RootModel = TestCase[]
