// Typescript interface generated by JSON Model Compiler
// for ./base-030
// see https://json-model.org/


/* simple regex props */
export interface RootModel {
	"#": string
	"/^(foo|bla)$/": number
}
