#! /bin/env node
// we may need require to load re2
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
//
// Generated by JSON Model Compiler version 2
// see https://github.com/clairey-zx81/json-model
//
import * as runtime from "json_model_runtime"
const JSON_MODEL_VERSION = "2";

var check_model_map = new Map()

// check $Val (.'$Val')
function json_model_2(val, path, rep)
{
    let res;
    // .'$Val'
    res = (typeof val === 'boolean' || val instanceof Boolean);
    if (! res)
    {
        rep !== null && rep.push(["not a bool [.'$Val']", path])
    }
    return res;
}

// check $Key (.'$Key')
function json_model_3(val, path, rep)
{
    let res;
    // .'$Key'
    res = runtime.jm_is_valid_url(val);
    if (! res)
    {
        rep !== null && rep.push(["unexpected $URL [.'$Key']", path])
    }
    return res;
}

// object .'$map'
function _jm_obj_0(val, path, rep)
{
    if (! (Object.prototype.toString.call(val) === '[object Object]'))
    {
        rep !== null && rep.push(["not an object [.'$map']", path])
        return false;
    }
    let res;
    for (const [prop, pval] of Object.entries(val))
    {
        let lpath_0 = path ? path.concat([prop]) : null;
        if (runtime.jm_is_valid_url(prop))
        {
            // handle 1 key props
            // .'$map'.'$URL'
            res = json_model_2(pval, (path ? lpath_0 : null), rep);
            if (! res)
            {
                rep !== null && rep.push(["unexpected $Val [.'$map'.'$URL']", (path ? lpath_0 : null)])
                return false;
            }
        }
        else
        {
            rep !== null && rep.push(["unexpected prop [.'$map']", (path ? lpath_0 : null)])
            return false;
        }
    }
    return true;
}

// check $map (.'$map')
function json_model_4(val, path, rep)
{
    let res;
    // .'$map'
    res = _jm_obj_0(val, path, rep);
    if (! res)
    {
        rep !== null && rep.push(["unexpected element [.'$map']", path])
    }
    return res;
}

// check $Ex08 (.'$Ex08')
function json_model_5(val, path, rep)
{
    let res;
    // .'$Ex08'
    // .'$Ex08'.'|'.0
    res = _jm_obj_0(val, path, rep);
    if (! res)
    {
        rep !== null && rep.push(["unexpected $map [.'$Ex08'.'|'.0]", path])
    }
    if (! res)
    {
        // .'$Ex08'.'|'.1
        res = runtime.jm_is_valid_url(val);
        if (! res)
        {
            rep !== null && rep.push(["unexpected $URL [.'$Ex08'.'|'.1]", path])
        }
        if (! res)
        {
            // .'$Ex08'.'|'.2
            res = json_model_2(val, path, rep);
            if (! res)
            {
                rep !== null && rep.push(["unexpected $Val [.'$Ex08'.'|'.2]", path])
            }
        }
    }
    if (res)
    {
        if (rep !== null) rep.length = 0
    }
    else
    {
        rep !== null && rep.push(["no model matched [.'$Ex08'.'|']", path])
    }
    return res;
}

// check $ (.)
function json_model_1(val, path, rep)
{
    let res;
    // .
    res = json_model_5(val, path, rep);
    if (! res)
    {
        rep !== null && rep.push(["unexpected $Ex08 [.]", path])
    }
    return res;
}


var initialized = false

// differed module initializations
export function check_model_init()
{
    if (! initialized)
    {
        initialized = true;
        runtime.jm_set_rx(RegExp)
        check_model_map.set("", json_model_5)
        check_model_map.set("Val", json_model_2)
        check_model_map.set("Key", json_model_3)
        check_model_map.set("map", _jm_obj_0)
        check_model_map.set("Ex08", json_model_5)
    }
}

// differed module cleanup
export function check_model_free()
{
    if (initialized)
    {
        initialized = false;
    }
}

export function check_model(val, name, rep)
{
    let checker = check_model_map.get(name)
    if (checker === undefined)
        throw `no checker for "${name}"`
    let path = rep !== null ? [] : null

    return checker(val, path, rep)
}

// possibly run as main based on a guess
import main from "json_model_runtime/main.js"

if (import.meta.url.endsWith(process.argv[1]))
    main(check_model_init, check_model, check_model_free)
