//
// Generated by JSON Model Compiler version 2.0b1
// see https://github.com/clairey-zx81/json-model
//
import json_model.*;
import java.util.Map;
import java.util.Set;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.regex.Pattern;
import java.util.regex.Matcher;

public class ex_01 extends ModelChecker
{
    static public final String VERSION = "2.0b1";

    public Map<String, Checker> ex_01_map_pmap;

    // check $x1 (.'$x1')
    public boolean json_model_4(Object val, Path path, Report rep)
    {
        boolean res;
        // .'$x1'
        res = json.isString(val) && json.asString(val).compareTo("Susie") == 0;
        if (! res)
        {
            if (rep != null) rep.addEntry("unexpected _Susie [.'$x1']", path);
        }
        return res;
    }
    
    // check $x2 (.'$x2')
    public boolean json_model_5(Object val, Path path, Report rep)
    {
        boolean res;
        // .'$x2'
        res = json.isString(val) && json.asString(val).compareTo("Susie") == 0;
        if (! res)
        {
            if (rep != null) rep.addEntry("unexpected _Susie [.'$x2']", path);
        }
        return res;
    }
    
    // object .
    public boolean _jm_obj_0(Object val, Path path, Report rep)
    {
        if (! json.isObject(val))
        {
            if (rep != null) rep.addEntry("not an object [.]", path);
            return false;
        }
        boolean res;
        long must_count = 0;
        Iterator<String> prop_loop = json.objectIterator(val);
        while (prop_loop.hasNext())
        {
            String prop = prop_loop.next();
            Object pval = json.objectValue(val, prop);
            Path lpath_0 = new Path(prop, path);
            if (prop.compareTo("a") == 0)
            {
                // handle must a property
                must_count += 1;
                // .a
                res = json.isString(pval) && json.asString(pval).compareTo("Susie") == 0;
                if (! res)
                {
                    if (rep != null) rep.addEntry("unexpected _Susie [.a]", (path != null ? lpath_0 : null));
                }
                if (! res)
                {
                    if (rep != null) rep.addEntry("invalid mandatory prop value [.a]", (path != null ? lpath_0 : null));
                    return false;
                }
            }
            else if (prop.compareTo("b") == 0)
            {
                // handle must b property
                must_count += 1;
                // .b
                res = json.isString(pval) && json.asString(pval).compareTo("Susie") == 0;
                if (! res)
                {
                    if (rep != null) rep.addEntry("unexpected _Susie [.b]", (path != null ? lpath_0 : null));
                }
                if (! res)
                {
                    if (rep != null) rep.addEntry("invalid mandatory prop value [.b]", (path != null ? lpath_0 : null));
                    return false;
                }
            }
            else
            {
                if (rep != null) rep.addEntry("unexpected prop [.]", (path != null ? lpath_0 : null));
                return false;
            }
        }
        if (must_count != 2)
        {
            if (rep != null)
            {
                if (! json.objectHasProp(val, "a"))
                {
                    if (rep != null) rep.addEntry("missing mandatory prop <a> [.]", path);
                }
                if (! json.objectHasProp(val, "b"))
                {
                    if (rep != null) rep.addEntry("missing mandatory prop <b> [.]", path);
                }
            }
            return false;
        }
        return true;
    }
    
    // check $ (.)
    public boolean json_model_1(Object val, Path path, Report rep)
    {
        boolean res;
        // .
        res = _jm_obj_0(val, path, rep);
        if (! res)
        {
            if (rep != null) rep.addEntry("unexpected element [.]", path);
        }
        return res;
    }
    

    public void init(JSON json)
    {
        if (!initialized)
        {
            try {
            ex_01_map_pmap = new HashMap<String, Checker>();
            ex_01_map_pmap.put("", new Checker() { public boolean call(Object o, Path p, Report r) { return json_model_1(o, p, r);} });
            ex_01_map_pmap.put("x1", new Checker() { public boolean call(Object o, Path p, Report r) { return json_model_4(o, p, r);} });
            ex_01_map_pmap.put("x2", new Checker() { public boolean call(Object o, Path p, Report r) { return json_model_5(o, p, r);} });
                super.init(json);
            }
            catch (Exception e) {
                throw new Error("cannot initialized model checker: " + e);
            }
        }
    }

    public void free()
    {
        if (initialized)
        {
            super.free();
            ex_01_map_pmap = null;
        }
    }

    public Checker get(String name)
    {
        return ex_01_map_pmap.get(name);
    }

    static public void main(String[] args) throws Exception
    {
        ModelChecker checker = new ex_01();
        Main.main("ex_01", checker, VERSION, args);
    }
}
