// Typescript interface generated by JSON Model Compiler
// for ./optnull
// see https://json-model.org/

/* optional prop which may be null */
export interface RootModel {
	null?: (null | "NULL" | "NOPE")
}
