//
// Generated by JSON Model Compiler version 2
// see https://github.com/clairey-zx81/json-model
//
import 'dart:convert';
import 'dart:io';
import 'dart:core';
// Import the helper library generated nearby
import 'package:json_model_runtime/json_model.dart' as runtime;
import 'package:json_model_runtime/main.dart';

//
// Generated JSON Model Validator
//
const String JSON_MODEL_VERSION = "2";

var check_model_map = <String, Function>{};

// check $ (.)
bool json_model_1(dynamic val, List<dynamic>? path, List<dynamic>? rep)
{
    bool res;
    // .
    // remove duplicate xor list
    bool is_0;
    res = true;
    // .'^'.1
    is_0 = (val is int) && val >= 0;
    if (! is_0)
    {
        rep?.add(["not a 0 strict int [.'^'.1]", path]);
    }
    res = ! is_0;
    if (res)
    {
        // .'^'.4
        is_0 = (val is int) && val >= 1;
        if (! is_0)
        {
            rep?.add(["not a 1 strict int [.'^'.4]", path]);
        }
        res = ! is_0;
    }
    if (res)
    {
        // .'^'.7
        is_0 = (val is String);
        if (! is_0)
        {
            rep?.add(["unexpected string [.'^'.7]", path]);
        }
        res = ! is_0;
    }
    res = false;
    rep?.add(["not one model match [.'^']", path]);
    return res;
}


// dart_init.dart
class GlobalState {
  static bool initializer = false;
}

Function? check_model_fun(String name) {
  return check_model_map[name];
}


void check_model_init() {
  if (!GlobalState.initializer){
    GlobalState.initializer = true;
  }
        check_model_map[""] = json_model_1;
}

// dart_free.dart
void check_model_free() {
  GlobalState.initializer = true;
}


void main(List<String> args) {
  runValidation(
    args,
    check_model_init,
    check_model_fun,
    check_model_free,
  );
}
