// Typescript interface generated by JSON Model Compiler
// for ./comments
// see https://json-model.org/


/*
 * This is a
 * multiline
 * comment.
 */
export interface RootModel {
	hello: string
	world: string
}
