#! /usr/bin/perl
#
# Generated by JSON Model Compiler version 2
# see https://github.com/clairey-zx81/json-model
#
use strict;
use warnings;
no warnings "uninitialized";
use re::engine::RE2;
use JSON::JsonModel;
use constant JMC_VERSION => '2';


sub json_model_2($$$);
sub json_model_3($$$);
sub json_model_4($$$);
sub json_model_5($$$);
sub json_model_6($$$);
sub json_model_7($$$);
sub json_model_8($$$);
sub json_model_9($$$);
sub json_model_10($$$);
my %_jm_map_0;
sub json_model_11($$$);
sub json_model_12($$$);
sub json_model_13($$$);
sub json_model_14($$$);
my %_jm_map_1;
sub json_model_1($$$);
my %check_model_map;

# check $position (.'$position')
sub json_model_2($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$position'
    my $res = jm_is_array($val);
    if ($res)
    {
        my $size_0 = scalar @$val;
        if ($size_0 >= 2 && $size_0 <= 3)
        {
            # unrolled prefix type check
            my $item_0 = $$val[0];
            my $item_1 = $$val[1];
            $res = jm_is_numeric($item_0) && jm_is_numeric($item_1);
            # optional remaining item
            if ($res && $size_0 == 3)
            {
                my $item_2 = $$val[2];
                $res = jm_is_numeric($item_2);
            }
        }
        else
        {
            $res = 0;
        }
    }
    else
    {
        $res = 0;
    }
    return $res;
}

# check $coord_array (.'$coord_array')
sub json_model_3($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$coord_array'
    # .'$coord_array'.'@'
    my $res = jm_is_array($val);
    if ($res)
    {
        for my $arr_0_idx (0 .. $#$val)
        {
            my $arr_0_item = $$val[$arr_0_idx];
            # .'$coord_array'.'@'.0
            $res = json_model_2($arr_0_item, undef, undef);
            if (! $res)
            {
                last;
            }
        }
    }
    if ($res)
    {
        my $ival_0 = scalar @$val;
        $res = $ival_0 >= 2;
    }
    return $res;
}

# check $linear_ring (.'$linear_ring')
sub json_model_4($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$linear_ring'
    # .'$linear_ring'.'@'
    my $res = jm_is_array($val);
    if ($res)
    {
        for my $arr_1_idx (0 .. $#$val)
        {
            my $arr_1_item = $$val[$arr_1_idx];
            # .'$linear_ring'.'@'.0
            $res = json_model_2($arr_1_item, undef, undef);
            if (! $res)
            {
                last;
            }
        }
    }
    if ($res)
    {
        my $ival_1 = scalar @$val;
        $res = $ival_1 >= 4;
    }
    return $res;
}

# check $Point (.'$Point')
sub json_model_5($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$Point'
    # check open must/may only props
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pval;
    if (! exists $$val{'type'})
    {
        return 0;
    }
    $pval = $$val{'type'};
    # .'$Point'.type
    my $res = jm_is_string($pval) && $pval eq 'Point';
    if (! $res)
    {
        return 0;
    }
    if (! exists $$val{'coordinates'})
    {
        return 0;
    }
    $pval = $$val{'coordinates'};
    # .'$Point'.coordinates
    $res = json_model_2($pval, undef, undef);
    if (! $res)
    {
        return 0;
    }
    if (exists $$val{'bbox'})
    {
        $pval = $$val{'bbox'};
        # .'$Point'.bbox
        $res = jm_is_array($pval);
        if ($res)
        {
            for my $arr_2_idx (0 .. $#$pval)
            {
                my $arr_2_item = $$pval[$arr_2_idx];
                # .'$Point'.bbox.0
                $res = jm_is_numeric($arr_2_item);
                if (! $res)
                {
                    last;
                }
            }
        }
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}

# check $MultiPoint (.'$MultiPoint')
sub json_model_6($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$MultiPoint'
    # check open must/may only props
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pval;
    if (! exists $$val{'type'})
    {
        return 0;
    }
    $pval = $$val{'type'};
    # .'$MultiPoint'.type
    my $res = jm_is_string($pval) && $pval eq 'MultiPoint';
    if (! $res)
    {
        return 0;
    }
    if (! exists $$val{'coordinates'})
    {
        return 0;
    }
    $pval = $$val{'coordinates'};
    # .'$MultiPoint'.coordinates
    $res = jm_is_array($pval);
    if ($res)
    {
        for my $arr_3_idx (0 .. $#$pval)
        {
            my $arr_3_item = $$pval[$arr_3_idx];
            # .'$MultiPoint'.coordinates.0
            $res = json_model_2($arr_3_item, undef, undef);
            if (! $res)
            {
                last;
            }
        }
    }
    if (! $res)
    {
        return 0;
    }
    if (exists $$val{'bbox'})
    {
        $pval = $$val{'bbox'};
        # .'$MultiPoint'.bbox
        $res = jm_is_array($pval);
        if ($res)
        {
            for my $arr_4_idx (0 .. $#$pval)
            {
                my $arr_4_item = $$pval[$arr_4_idx];
                # .'$MultiPoint'.bbox.0
                $res = jm_is_numeric($arr_4_item);
                if (! $res)
                {
                    last;
                }
            }
        }
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}

# check $LineString (.'$LineString')
sub json_model_7($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$LineString'
    # check open must/may only props
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pval;
    if (! exists $$val{'type'})
    {
        return 0;
    }
    $pval = $$val{'type'};
    # .'$LineString'.type
    my $res = jm_is_string($pval) && $pval eq 'LineString';
    if (! $res)
    {
        return 0;
    }
    if (! exists $$val{'coordinates'})
    {
        return 0;
    }
    $pval = $$val{'coordinates'};
    # .'$LineString'.coordinates
    $res = json_model_3($pval, undef, undef);
    if (! $res)
    {
        return 0;
    }
    if (exists $$val{'bbox'})
    {
        $pval = $$val{'bbox'};
        # .'$LineString'.bbox
        $res = jm_is_array($pval);
        if ($res)
        {
            for my $arr_5_idx (0 .. $#$pval)
            {
                my $arr_5_item = $$pval[$arr_5_idx];
                # .'$LineString'.bbox.0
                $res = jm_is_numeric($arr_5_item);
                if (! $res)
                {
                    last;
                }
            }
        }
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}

# check $MultiLineString (.'$MultiLineString')
sub json_model_8($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$MultiLineString'
    # check open must/may only props
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pval;
    if (! exists $$val{'type'})
    {
        return 0;
    }
    $pval = $$val{'type'};
    # .'$MultiLineString'.type
    my $res = jm_is_string($pval) && $pval eq 'MultiLineString';
    if (! $res)
    {
        return 0;
    }
    if (! exists $$val{'coordinates'})
    {
        return 0;
    }
    $pval = $$val{'coordinates'};
    # .'$MultiLineString'.coordinates
    $res = jm_is_array($pval);
    if ($res)
    {
        for my $arr_6_idx (0 .. $#$pval)
        {
            my $arr_6_item = $$pval[$arr_6_idx];
            # .'$MultiLineString'.coordinates.0
            $res = json_model_3($arr_6_item, undef, undef);
            if (! $res)
            {
                last;
            }
        }
    }
    if (! $res)
    {
        return 0;
    }
    if (exists $$val{'bbox'})
    {
        $pval = $$val{'bbox'};
        # .'$MultiLineString'.bbox
        $res = jm_is_array($pval);
        if ($res)
        {
            for my $arr_7_idx (0 .. $#$pval)
            {
                my $arr_7_item = $$pval[$arr_7_idx];
                # .'$MultiLineString'.bbox.0
                $res = jm_is_numeric($arr_7_item);
                if (! $res)
                {
                    last;
                }
            }
        }
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}

# check $Polygon (.'$Polygon')
sub json_model_9($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$Polygon'
    # check open must/may only props
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pval;
    if (! exists $$val{'type'})
    {
        return 0;
    }
    $pval = $$val{'type'};
    # .'$Polygon'.type
    my $res = jm_is_string($pval) && $pval eq 'Polygon';
    if (! $res)
    {
        return 0;
    }
    if (! exists $$val{'coordinates'})
    {
        return 0;
    }
    $pval = $$val{'coordinates'};
    # .'$Polygon'.coordinates
    $res = jm_is_array($pval);
    if ($res)
    {
        for my $arr_8_idx (0 .. $#$pval)
        {
            my $arr_8_item = $$pval[$arr_8_idx];
            # .'$Polygon'.coordinates.0
            $res = json_model_4($arr_8_item, undef, undef);
            if (! $res)
            {
                last;
            }
        }
    }
    if (! $res)
    {
        return 0;
    }
    if (exists $$val{'bbox'})
    {
        $pval = $$val{'bbox'};
        # .'$Polygon'.bbox
        $res = jm_is_array($pval);
        if ($res)
        {
            for my $arr_9_idx (0 .. $#$pval)
            {
                my $arr_9_item = $$pval[$arr_9_idx];
                # .'$Polygon'.bbox.0
                $res = jm_is_numeric($arr_9_item);
                if (! $res)
                {
                    last;
                }
            }
        }
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}

# check $MultiPolygon (.'$MultiPolygon')
sub json_model_10($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$MultiPolygon'
    # check open must/may only props
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pval;
    if (! exists $$val{'type'})
    {
        return 0;
    }
    $pval = $$val{'type'};
    # .'$MultiPolygon'.type
    my $res = jm_is_string($pval) && $pval eq 'MultiPolygon';
    if (! $res)
    {
        return 0;
    }
    if (! exists $$val{'coordinates'})
    {
        return 0;
    }
    $pval = $$val{'coordinates'};
    # .'$MultiPolygon'.coordinates
    $res = jm_is_array($pval);
    if ($res)
    {
        for my $arr_10_idx (0 .. $#$pval)
        {
            my $arr_10_item = $$pval[$arr_10_idx];
            # .'$MultiPolygon'.coordinates.0
            $res = jm_is_array($arr_10_item);
            if ($res)
            {
                for my $arr_11_idx (0 .. $#$arr_10_item)
                {
                    my $arr_11_item = $$arr_10_item[$arr_11_idx];
                    # .'$MultiPolygon'.coordinates.0.0
                    $res = json_model_4($arr_11_item, undef, undef);
                    if (! $res)
                    {
                        last;
                    }
                }
            }
            if (! $res)
            {
                last;
            }
        }
    }
    if (! $res)
    {
        return 0;
    }
    if (exists $$val{'bbox'})
    {
        $pval = $$val{'bbox'};
        # .'$MultiPolygon'.bbox
        $res = jm_is_array($pval);
        if ($res)
        {
            for my $arr_12_idx (0 .. $#$pval)
            {
                my $arr_12_item = $$pval[$arr_12_idx];
                # .'$MultiPolygon'.bbox.0
                $res = jm_is_numeric($arr_12_item);
                if (! $res)
                {
                    last;
                }
            }
        }
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}


# check $geometry (.'$geometry')
sub json_model_11($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$geometry'
    my $res = jm_is_object($val);
    if ($res)
    {
        my $tag_0;
        if (defined($tag_0 = $$val{'type'}))
        {
            my $fun_0 = $_jm_map_0{$tag_0};
            $res = defined($fun_0) && &$fun_0($val, undef, undef);
        }
        else
        {
            $res = 0;
        }
    }
    return $res;
}

# check $GeometryCollection (.'$GeometryCollection')
sub json_model_12($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$GeometryCollection'
    # check open must/may only props
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pval;
    if (! exists $$val{'type'})
    {
        return 0;
    }
    $pval = $$val{'type'};
    # .'$GeometryCollection'.type
    my $res = jm_is_string($pval) && $pval eq 'GeometryCollection';
    if (! $res)
    {
        return 0;
    }
    if (! exists $$val{'geometries'})
    {
        return 0;
    }
    $pval = $$val{'geometries'};
    # .'$GeometryCollection'.geometries
    $res = jm_is_array($pval);
    if ($res)
    {
        for my $arr_13_idx (0 .. $#$pval)
        {
            my $arr_13_item = $$pval[$arr_13_idx];
            # .'$GeometryCollection'.geometries.0
            $res = json_model_11($arr_13_item, undef, undef);
            if (! $res)
            {
                last;
            }
        }
    }
    if (! $res)
    {
        return 0;
    }
    if (exists $$val{'bbox'})
    {
        $pval = $$val{'bbox'};
        # .'$GeometryCollection'.bbox
        $res = jm_is_array($pval);
        if ($res)
        {
            for my $arr_14_idx (0 .. $#$pval)
            {
                my $arr_14_item = $$pval[$arr_14_idx];
                # .'$GeometryCollection'.bbox.0
                $res = jm_is_numeric($arr_14_item);
                if (! $res)
                {
                    last;
                }
            }
        }
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}

# check $Feature (.'$Feature')
sub json_model_13($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$Feature'
    # check open must/may only props
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pval;
    if (! exists $$val{'type'})
    {
        return 0;
    }
    $pval = $$val{'type'};
    # .'$Feature'.type
    my $res = jm_is_string($pval) && $pval eq 'Feature';
    if (! $res)
    {
        return 0;
    }
    if (! exists $$val{'geometry'})
    {
        return 0;
    }
    $pval = $$val{'geometry'};
    # .'$Feature'.geometry
    # .'$Feature'.geometry.'|'.0
    # .'$Feature'.geometry.'|'.1
    # .'$Feature'.geometry.'|'.2
    $res = !defined($pval) || json_model_11($pval, undef, undef) || json_model_12($pval, undef, undef);
    if (! $res)
    {
        return 0;
    }
    if (! exists $$val{'properties'})
    {
        return 0;
    }
    $pval = $$val{'properties'};
    # .'$Feature'.properties
    # .'$Feature'.properties.'|'.0
    # .'$Feature'.properties.'|'.1
    $res = !defined($pval) || jm_is_object($pval);
    if (! $res)
    {
        return 0;
    }
    if (exists $$val{'id'})
    {
        $pval = $$val{'id'};
        # .'$Feature'.id
        # .'$Feature'.id.'|'.0
        # .'$Feature'.id.'|'.1
        $res = jm_is_string($pval) || jm_is_numeric($pval);
        if (! $res)
        {
            return 0;
        }
    }
    if (exists $$val{'bbox'})
    {
        $pval = $$val{'bbox'};
        # .'$Feature'.bbox
        $res = jm_is_array($pval);
        if ($res)
        {
            for my $arr_15_idx (0 .. $#$pval)
            {
                my $arr_15_item = $$pval[$arr_15_idx];
                # .'$Feature'.bbox.0
                $res = jm_is_numeric($arr_15_item);
                if (! $res)
                {
                    last;
                }
            }
        }
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}

# check $FeatureCollection (.'$FeatureCollection')
sub json_model_14($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$FeatureCollection'
    # check open must/may only props
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pval;
    if (! exists $$val{'type'})
    {
        return 0;
    }
    $pval = $$val{'type'};
    # .'$FeatureCollection'.type
    my $res = jm_is_string($pval) && $pval eq 'FeatureCollection';
    if (! $res)
    {
        return 0;
    }
    if (! exists $$val{'features'})
    {
        return 0;
    }
    $pval = $$val{'features'};
    # .'$FeatureCollection'.features
    $res = jm_is_array($pval);
    if ($res)
    {
        for my $arr_16_idx (0 .. $#$pval)
        {
            my $arr_16_item = $$pval[$arr_16_idx];
            # .'$FeatureCollection'.features.0
            $res = json_model_13($arr_16_item, undef, undef);
            if (! $res)
            {
                last;
            }
        }
    }
    if (! $res)
    {
        return 0;
    }
    if (exists $$val{'bbox'})
    {
        $pval = $$val{'bbox'};
        # .'$FeatureCollection'.bbox
        $res = jm_is_array($pval);
        if ($res)
        {
            for my $arr_17_idx (0 .. $#$pval)
            {
                my $arr_17_item = $$pval[$arr_17_idx];
                # .'$FeatureCollection'.bbox.0
                $res = jm_is_numeric($arr_17_item);
                if (! $res)
                {
                    last;
                }
            }
        }
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}


# check $ (.)
sub json_model_1($$$)
{
    my ($val, $path, $rep) = @_;
    # Easy Geo JSON Model JSON_MODEL_LOOSE_FLOAT
    # .
    my $res = jm_is_object($val);
    if ($res)
    {
        my $tag_1;
        if (defined($tag_1 = $$val{'type'}))
        {
            my $fun_1 = $_jm_map_1{$tag_1};
            $res = defined($fun_1) && &$fun_1($val, undef, undef);
        }
        else
        {
            $res = 0;
        }
    }
    return $res || json_model_11($val, undef, undef);
}


# initialization of global variables

our $initialized = 0;

sub check_model_init()
{
    if (!$initialized)
    {
        $initialized = 1;
        %_jm_map_0 = (
            'Point' => \&json_model_5,
            'MultiPoint' => \&json_model_6,
            'LineString' => \&json_model_7,
            'MultiLineString' => \&json_model_8,
            'Polygon' => \&json_model_9,
            'MultiPolygon' => \&json_model_10,
        );
        %_jm_map_1 = (
            'GeometryCollection' => \&json_model_12,
            'Feature' => \&json_model_13,
            'FeatureCollection' => \&json_model_14,
        );
        %check_model_map = (
            '' => \&json_model_1,
            'position' => \&json_model_2,
            'coord_array' => \&json_model_3,
            'linear_ring' => \&json_model_4,
            'Point' => \&json_model_5,
            'MultiPoint' => \&json_model_6,
            'LineString' => \&json_model_7,
            'MultiLineString' => \&json_model_8,
            'Polygon' => \&json_model_9,
            'MultiPolygon' => \&json_model_10,
            'geometry' => \&json_model_11,
            'GeometryCollection' => \&json_model_12,
            'Feature' => \&json_model_13,
            'FeatureCollection' => \&json_model_14,
        );
    }
}

sub check_model_free()
{
    if ($initialized)
    {
        $initialized = 0;
        %_jm_map_0 = ();
        %_jm_map_1 = ();
        %check_model_map = ();
    }
}

sub check_model_mapper($)
{
    my ($name) = @_;
    die "unexpected model name \"$name\"" unless exists $check_model_map{$name};
    return $check_model_map{$name};
}

sub check_model($$$)
{
    my ($json, $name, $rep) = @_;
    die "unexpected model name \"$name\"" unless exists $check_model_map{$name};
    my $path = defined $rep ? [] : undef;
    return $check_model_map{$name}($json, $path, $rep);
}

#
# SCRIPT EXECUTION
#
check_model_init();
jm_main(\&check_model, \%check_model_map, JMC_VERSION);
check_model_free();
