#! /usr/bin/perl
#
# Generated by JSON Model Compiler version 2
# see https://github.com/clairey-zx81/json-model
#
use utf8;
use strict;
use warnings;
no warnings "uninitialized";
use re::engine::RE2;
use JSON::JsonModel;
use constant JMC_VERSION => "2";


sub json_model_2($$$);
sub json_model_3($$$);
my %_jm_cst_0;
sub json_model_4($$$);
sub json_model_5($$$);
sub json_model_6($$$);
my %_jm_cst_1;
sub json_model_7($$$);
sub _jm_obj_0($$$);
sub _jm_obj_1($$$);
sub json_model_8($$$);
sub json_model_9($$$);
sub json_model_10($$$);
sub json_model_11($$$);
sub json_model_12($$$);
my %_jm_cst_2;
sub json_model_13($$$);
my %_jm_cst_3;
sub json_model_14($$$);
sub json_model_15($$$);
sub _jm_obj_2($$$);
sub json_model_16($$$);
sub _jm_obj_3($$$);
sub _jm_obj_4($$$);
sub _jm_obj_5($$$);
sub _jm_obj_6($$$);
sub json_model_1($$$);
my %check_model_map;

sub _jm_re_0($$$)
{
    my ($val, $path, $rep) = @_;
    my $res = $val =~ /./;
    return $res;
}

# check $neStr (.'$neStr')
sub json_model_2($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$neStr'
    # "/./"
    my $res = jm_is_string($val) && _jm_re_0($val, $path, $rep);
    push @$rep, ["unexpected value for model \"/./\" [.'\$neStr']", $path] if defined $rep and not $res;
    return $res;
}

# check $neStrList (.'$neStrList')
sub json_model_3($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$neStrList'
    # .'$neStrList'.'@'
    my $res = jm_is_array($val);
    if ($res)
    {
        for my $arr_0_idx (0 .. $#$val)
        {
            my $arr_0_item = $$val[$arr_0_idx];
            my $arr_0_lpath = defined $path ? [@{$path}, $arr_0_idx] : undef;
            # .'$neStrList'.'@'.0
            $res = json_model_2($arr_0_item, defined $path ? $arr_0_lpath : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$neStr\" [.'\$neStrList'.'\@'.0]", defined $path ? $arr_0_lpath : undef] if defined $rep;
                last;
            }
        }
    }
    if ($res)
    {
        my $ival_0 = scalar @$val;
        $res = jm_is_unique_array($val, $path, $rep) && $ival_0 >= 1;
        push @$rep, ["constraints failed [.'\$neStrList']", $path] if defined $rep and not $res;
    }
    else
    {
        push @$rep, ["not array or unexpected array [.'\$neStrList'.'\@']", $path] if defined $rep;
    }
    return $res;
}


# check $License (.'$License')
sub json_model_4($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$License'
    my $res = jm_is_string($val) && exists $_jm_cst_0{$val};
    push @$rep, ["value not in enum [.'\$License'.'|']", $path] if defined $rep and not $res;
    return $res;
}

# check $LicenseList (.'$LicenseList')
sub json_model_5($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$LicenseList'
    # .'$LicenseList'.'@'
    my $res = jm_is_array($val);
    if ($res)
    {
        for my $arr_1_idx (0 .. $#$val)
        {
            my $arr_1_item = $$val[$arr_1_idx];
            my $arr_1_lpath = defined $path ? [@{$path}, $arr_1_idx] : undef;
            # .'$LicenseList'.'@'.0
            $res = json_model_4($arr_1_item, defined $path ? $arr_1_lpath : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$License\" [.'\$LicenseList'.'\@'.0]", defined $path ? $arr_1_lpath : undef] if defined $rep;
                last;
            }
        }
    }
    if ($res)
    {
        my $ival_1 = scalar @$val;
        $res = jm_is_unique_array($val, $path, $rep) && $ival_1 >= 1;
        push @$rep, ["constraints failed [.'\$LicenseList']", $path] if defined $rep and not $res;
    }
    else
    {
        push @$rep, ["not array or unexpected array [.'\$LicenseList'.'\@']", $path] if defined $rep;
    }
    return $res;
}

sub _jm_re_1($$$)
{
    my ($val, $path, $rep) = @_;
    my $res = $val =~ /^[Xx]_/;
    return $res;
}

# check $Provide (.'$Provide')
sub json_model_6($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$Provide'
    unless (jm_is_object($val))
    {
        push @$rep, ["not an object [.'\$Provide']", $path] if defined $rep;
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        my $lpath_0 = defined $path ? [@{$path}, $prop] : undef;
        if ($prop eq "file")
        {
            # handle must file property
            $must_count++;
            # .'$Provide'.file
            $res = jm_is_string($pval);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\" [.'\$Provide'.file]", defined $path ? $lpath_0 : undef] if defined $rep;
                push @$rep, ["invalid mandatory prop value [.'\$Provide'.file]", defined $path ? $lpath_0 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "version")
        {
            # handle must version property
            $must_count++;
            # .'$Provide'.version
            $res = json_model_10($pval, defined $path ? $lpath_0 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$Version\" [.'\$Provide'.version]", defined $path ? $lpath_0 : undef] if defined $rep;
                push @$rep, ["invalid mandatory prop value [.'\$Provide'.version]", defined $path ? $lpath_0 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        if ($prop eq "abstract")
        {
            # handle may abstract property
            # .'$Provide'.abstract
            $res = jm_is_string($pval);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\" [.'\$Provide'.abstract]", defined $path ? $lpath_0 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.'\$Provide'.abstract]", defined $path ? $lpath_0 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "docfile")
        {
            # handle may docfile property
            # .'$Provide'.docfile
            $res = jm_is_string($pval);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\" [.'\$Provide'.docfile]", defined $path ? $lpath_0 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.'\$Provide'.docfile]", defined $path ? $lpath_0 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        if (_jm_re_1($prop, $path, $rep))
        {
            # handle 1 re props
            # .'$Provide'.'/^[Xx]_/'
            $res = 1;
        }
        else
        {
            push @$rep, ["unexpected prop [.'\$Provide']", defined $path ? $lpath_0 : undef] if defined $rep;
            return 0;
        }
    }
    if ($must_count != 2)
    {
        if (defined $rep)
        {
            push @$rep, ["missing mandatory prop <file> [.'\$Provide']", $path] if defined $rep and not exists $$val{"file"};
            push @$rep, ["missing mandatory prop <version> [.'\$Provide']", $path] if defined $rep and not exists $$val{"version"};
        }
        return 0;
    }
    return 1;
}


# check $Status (.'$Status')
sub json_model_7($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$Status'
    my $res = jm_is_string($val) && exists $_jm_cst_1{$val};
    push @$rep, ["value not in enum [.'\$Status'.'|']", $path] if defined $rep and not $res;
    return $res;
}

# object .'$Resources'.bugtracker
sub _jm_obj_0($$$)
{
    my ($val, $path, $rep) = @_;
    unless (jm_is_object($val))
    {
        push @$rep, ["not an object [.'\$Resources'.bugtracker]", $path] if defined $rep;
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        my $lpath_2 = defined $path ? [@{$path}, $prop] : undef;
        if ($prop eq "web")
        {
            # handle may web property
            # .'$Resources'.bugtracker.web
            $res = jm_is_string($pval) && jm_is_valid_url($pval, defined $path ? $lpath_2 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$URL\" [.'\$Resources'.bugtracker.web]", defined $path ? $lpath_2 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.'\$Resources'.bugtracker.web]", defined $path ? $lpath_2 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "mailto")
        {
            # handle may mailto property
            # .'$Resources'.bugtracker.mailto
            $res = jm_is_string($pval) && jm_is_email($pval, defined $path ? $lpath_2 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$EMAIL\" [.'\$Resources'.bugtracker.mailto]", defined $path ? $lpath_2 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.'\$Resources'.bugtracker.mailto]", defined $path ? $lpath_2 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        if (_jm_re_1($prop, $path, $rep))
        {
            # handle 1 re props
            # .'$Resources'.bugtracker.'/^[Xx]_/'
            $res = 1;
        }
        else
        {
            push @$rep, ["unexpected prop [.'\$Resources'.bugtracker]", defined $path ? $lpath_2 : undef] if defined $rep;
            return 0;
        }
    }
    return 1;
}

# object .'$Resources'.repository
sub _jm_obj_1($$$)
{
    my ($val, $path, $rep) = @_;
    unless (jm_is_object($val))
    {
        push @$rep, ["not an object [.'\$Resources'.repository]", $path] if defined $rep;
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        my $lpath_3 = defined $path ? [@{$path}, $prop] : undef;
        if ($prop eq "url")
        {
            # handle may url property
            # .'$Resources'.repository.url
            $res = jm_is_string($pval) && jm_is_valid_url($pval, defined $path ? $lpath_3 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$URL\" [.'\$Resources'.repository.url]", defined $path ? $lpath_3 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.'\$Resources'.repository.url]", defined $path ? $lpath_3 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "web")
        {
            # handle may web property
            # .'$Resources'.repository.web
            $res = jm_is_string($pval) && jm_is_valid_url($pval, defined $path ? $lpath_3 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$URL\" [.'\$Resources'.repository.web]", defined $path ? $lpath_3 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.'\$Resources'.repository.web]", defined $path ? $lpath_3 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "type")
        {
            # handle may type property
            # .'$Resources'.repository.type
            # "/./"
            $res = jm_is_string($pval) && _jm_re_0($pval, defined $path ? $lpath_3 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"/./\" [.'\$Resources'.repository.type]", defined $path ? $lpath_3 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.'\$Resources'.repository.type]", defined $path ? $lpath_3 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        push @$rep, ["unexpected prop [.'\$Resources'.repository]", defined $path ? $lpath_3 : undef] if defined $rep;
        return 0;
    }
    return 1;
}

# check $Resources (.'$Resources')
sub json_model_8($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$Resources'
    unless (jm_is_object($val))
    {
        push @$rep, ["not an object [.'\$Resources']", $path] if defined $rep;
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        my $lpath_1 = defined $path ? [@{$path}, $prop] : undef;
        if ($prop eq "homepage")
        {
            # handle may homepage property
            # .'$Resources'.homepage
            $res = jm_is_string($pval) && jm_is_valid_url($pval, defined $path ? $lpath_1 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$URL\" [.'\$Resources'.homepage]", defined $path ? $lpath_1 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.'\$Resources'.homepage]", defined $path ? $lpath_1 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "bugtracker")
        {
            # handle may bugtracker property
            # .'$Resources'.bugtracker
            $res = _jm_obj_0($pval, defined $path ? $lpath_1 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected element [.'\$Resources'.bugtracker]", defined $path ? $lpath_1 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.'\$Resources'.bugtracker]", defined $path ? $lpath_1 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "repository")
        {
            # handle may repository property
            # .'$Resources'.repository
            $res = _jm_obj_1($pval, defined $path ? $lpath_1 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected element [.'\$Resources'.repository]", defined $path ? $lpath_1 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.'\$Resources'.repository]", defined $path ? $lpath_1 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        push @$rep, ["unexpected prop [.'\$Resources']", defined $path ? $lpath_1 : undef] if defined $rep;
        return 0;
    }
    return 1;
}

sub _jm_re_2($$$)
{
    my ($val, $path, $rep) = @_;
    my $res = $val =~ /^\d+\.\d+\.\d+[-_A-Za-z0-9]*$/;
    return $res;
}

# check $SemVer (.'$SemVer')
sub json_model_9($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$SemVer'
    # "/^\\d+\\.\\d+\\.\\d+[-_A-Za-z0-9]*$/"
    my $res = jm_is_string($val) && _jm_re_2($val, $path, $rep);
    push @$rep, ["unexpected value for model \"/^\\\\d+\\\\.\\\\d+\\\\.\\\\d+[-_A-Za-z0-9]*\\\$/\" [.'\$SemVer']", $path] if defined $rep and not $res;
    return $res;
}

# check $Version (.'$Version')
sub json_model_10($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$Version'
    # .'$Version'.'|'.0
    my $res = json_model_9($val, $path, $rep);
    unless ($res)
    {
        push @$rep, ["unexpected value for model \"\\\$SemVer\" [.'\$Version'.'|'.0]", $path] if defined $rep;
        # .'$Version'.'|'.1
        $res = jm_is_integer($val) && $val == 0;
        push @$rep, ["unexpected value for model \"=0\" [.'\$Version'.'|'.1]", $path] if defined $rep and not $res;
    }
    if ($res)
    {
        @$rep = () if defined $rep;
    }
    else
    {
        push @$rep, ["no model matched [.'\$Version'.'|']", $path] if defined $rep;
    }
    return $res;
}

sub _jm_re_3($$$)
{
    my ($val, $path, $rep) = @_;
    my $res = $val =~ /^(<=|<|>=|>|!=|==)$/;
    return $res;
}

# check $Ops (.'$Ops')
sub json_model_11($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$Ops'
    # "/^(<=|<|>=|>|!=|==)$/"
    my $res = jm_is_string($val) && _jm_re_3($val, $path, $rep);
    push @$rep, ["unexpected value for model \"/^(<=|<|>=|>|!=|==)\\\$/\" [.'\$Ops']", $path] if defined $rep and not $res;
    return $res;
}

sub _jm_re_4($$$)
{
    my ($val, $path, $rep) = @_;
    my $res = $val =~ /^\s*(<=|<|>=|>|!=|==)\s*(\d+\.\d+\.\d+[-_A-Za-z0-9]*)\s*(,\s*(<=|<|>=|>|!=|==)\s*(\d+\.\d+\.\d+[-_A-Za-z0-9]*))*\s*$/;
    return $res;
}

# check $VersionRange (.'$VersionRange')
sub json_model_12($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$VersionRange'
    # "/^\\s*(<=|<|>=|>|!=|==)\\s*(\\d+\\.\\d+\\.\\d+[-_A-Za-z0-9]*)\\s*(,\\s*(<=|<|>=|>|!=|==)\\s*(\\d+\\.\\d+\\.\\d+[-_A-Za-z0-9]*))*\\s*$/"
    my $res = jm_is_string($val) && _jm_re_4($val, $path, $rep);
    push @$rep, ["unexpected value for model \"/^\\\\s*(<=|<|>=|>|!=|==)\\\\s*(\\\\d+\\\\.\\\\d+\\\\.\\\\d+[-_A-Za-z0-9]*)\\\\s*(,\\\\s*(<=|<|>=|>|!=|==)\\\\s*(\\\\d+\\\\.\\\\d+\\\\.\\\\d+[-_A-Za-z0-9]*))*\\\\s*\\\$/\" [.'\$VersionRange']", $path] if defined $rep and not $res;
    return $res;
}


# check $Phase (.'$Phase')
sub json_model_13($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$Phase'
    my $res = jm_is_string($val) && exists $_jm_cst_2{$val};
    push @$rep, ["value not in enum [.'\$Phase'.'|']", $path] if defined $rep and not $res;
    return $res;
}


# check $Relation (.'$Relation')
sub json_model_14($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$Relation'
    my $res = jm_is_string($val) && exists $_jm_cst_3{$val};
    push @$rep, ["value not in enum [.'\$Relation'.'|']", $path] if defined $rep and not $res;
    return $res;
}

# check $Prereq (.'$Prereq')
sub json_model_15($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$Prereq'
    unless (jm_is_object($val))
    {
        push @$rep, ["not an object [.'\$Prereq']", $path] if defined $rep;
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        my $lpath_4 = defined $path ? [@{$path}, $prop] : undef;
        # handle other props
        # .'$Prereq'.''
        # .'$Prereq'.''.'|'.0
        $res = json_model_10($pval, defined $path ? $lpath_4 : undef, $rep);
        unless ($res)
        {
            push @$rep, ["unexpected value for model \"\\\$Version\" [.'\$Prereq'.''.'|'.0]", defined $path ? $lpath_4 : undef] if defined $rep;
            # .'$Prereq'.''.'|'.1
            $res = json_model_12($pval, defined $path ? $lpath_4 : undef, $rep);
            push @$rep, ["unexpected value for model \"\\\$VersionRange\" [.'\$Prereq'.''.'|'.1]", defined $path ? $lpath_4 : undef] if defined $rep and not $res;
        }
        if ($res)
        {
            @$rep = () if defined $rep;
        }
        else
        {
            push @$rep, ["no model matched [.'\$Prereq'.''.'|']", defined $path ? $lpath_4 : undef] if defined $rep;
            return 0;
        }
    }
    return 1;
}

# object .'$Prereqs'.'$Phase'
sub _jm_obj_2($$$)
{
    my ($val, $path, $rep) = @_;
    unless (jm_is_object($val))
    {
        push @$rep, ["not an object [.'\$Prereqs'.'\$Phase']", $path] if defined $rep;
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        my $lpath_6 = defined $path ? [@{$path}, $prop] : undef;
        if (json_model_14($prop, defined $path ? $lpath_6 : undef, $rep))
        {
            # handle 1 key props
            # .'$Prereqs'.'$Phase'.'$Relation'
            $res = json_model_15($pval, defined $path ? $lpath_6 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$Prereq\" [.'\$Prereqs'.'\$Phase'.'\$Relation']", defined $path ? $lpath_6 : undef] if defined $rep;
                return 0;
            }
        }
        elsif (_jm_re_1($prop, $path, $rep))
        {
            # handle 1 re props
            # .'$Prereqs'.'$Phase'.'/^[Xx]_/'
            $res = 1;
        }
        else
        {
            push @$rep, ["unexpected prop [.'\$Prereqs'.'\$Phase']", defined $path ? $lpath_6 : undef] if defined $rep;
            return 0;
        }
    }
    return 1;
}

# check $Prereqs (.'$Prereqs')
sub json_model_16($$$)
{
    my ($val, $path, $rep) = @_;
    # .'$Prereqs'
    unless (jm_is_object($val))
    {
        push @$rep, ["not an object [.'\$Prereqs']", $path] if defined $rep;
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        my $lpath_5 = defined $path ? [@{$path}, $prop] : undef;
        if (json_model_13($prop, defined $path ? $lpath_5 : undef, $rep))
        {
            # handle 1 key props
            # .'$Prereqs'.'$Phase'
            $res = _jm_obj_2($pval, defined $path ? $lpath_5 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected element [.'\$Prereqs'.'\$Phase']", defined $path ? $lpath_5 : undef] if defined $rep;
                return 0;
            }
        }
        elsif (_jm_re_1($prop, $path, $rep))
        {
            # handle 1 re props
            # .'$Prereqs'.'/^[Xx]_/'
            $res = 1;
        }
        else
        {
            push @$rep, ["unexpected prop [.'\$Prereqs']", defined $path ? $lpath_5 : undef] if defined $rep;
            return 0;
        }
    }
    return 1;
}

# object .license.'|'.2
sub _jm_obj_3($$$)
{
    my ($val, $path, $rep) = @_;
    unless (jm_is_object($val))
    {
        push @$rep, ["not an object [.license.'|'.2]", $path] if defined $rep;
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        my $lpath_8 = defined $path ? [@{$path}, $prop] : undef;
        # handle other props
        # .license.'|'.2.''
        $res = jm_is_string($pval) && jm_is_valid_url($pval, defined $path ? $lpath_8 : undef, $rep);
        unless ($res)
        {
            push @$rep, ["unexpected value for model \"\\\$URL\" [.license.'|'.2.'']", defined $path ? $lpath_8 : undef] if defined $rep;
            return 0;
        }
    }
    return 1;
}

# object .provides
sub _jm_obj_4($$$)
{
    my ($val, $path, $rep) = @_;
    unless (jm_is_object($val))
    {
        push @$rep, ["not an object [.provides]", $path] if defined $rep;
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        my $lpath_9 = defined $path ? [@{$path}, $prop] : undef;
        # handle other props
        # .provides.''
        $res = json_model_6($pval, defined $path ? $lpath_9 : undef, $rep);
        unless ($res)
        {
            push @$rep, ["unexpected value for model \"\\\$Provide\" [.provides.'']", defined $path ? $lpath_9 : undef] if defined $rep;
            return 0;
        }
    }
    return 1;
}

# object .'meta-spec'
sub _jm_obj_5($$$)
{
    my ($val, $path, $rep) = @_;
    unless (jm_is_object($val))
    {
        push @$rep, ["not an object [.'meta-spec']", $path] if defined $rep;
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        my $lpath_10 = defined $path ? [@{$path}, $prop] : undef;
        if ($prop eq "version")
        {
            # handle must version property
            $must_count++;
            # .'meta-spec'.version
            $res = jm_is_string($pval) && $pval eq "1.0.0";
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"_1.0.0\" [.'meta-spec'.version]", defined $path ? $lpath_10 : undef] if defined $rep;
                push @$rep, ["invalid mandatory prop value [.'meta-spec'.version]", defined $path ? $lpath_10 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        if ($prop eq "url")
        {
            # handle may url property
            # .'meta-spec'.url
            $res = jm_is_string($pval) && jm_is_valid_url($pval, defined $path ? $lpath_10 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$URL\" [.'meta-spec'.url]", defined $path ? $lpath_10 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.'meta-spec'.url]", defined $path ? $lpath_10 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        if (_jm_re_1($prop, $path, $rep))
        {
            # handle 1 re props
            # .'meta-spec'.'/^[Xx]_/'
            $res = 1;
        }
        else
        {
            push @$rep, ["unexpected prop [.'meta-spec']", defined $path ? $lpath_10 : undef] if defined $rep;
            return 0;
        }
    }
    if ($must_count != 1)
    {
        if (defined $rep)
        {
            push @$rep, ["missing mandatory prop <version> [.'meta-spec']", $path] if defined $rep and not exists $$val{"version"};
        }
        return 0;
    }
    return 1;
}

# object .no_index
sub _jm_obj_6($$$)
{
    my ($val, $path, $rep) = @_;
    unless (jm_is_object($val))
    {
        push @$rep, ["not an object [.no_index]", $path] if defined $rep;
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        my $lpath_11 = defined $path ? [@{$path}, $prop] : undef;
        if ($prop eq "file")
        {
            # handle may file property
            # .no_index.file
            $res = json_model_3($pval, defined $path ? $lpath_11 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$neStrList\" [.no_index.file]", defined $path ? $lpath_11 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.no_index.file]", defined $path ? $lpath_11 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "directory")
        {
            # handle may directory property
            # .no_index.directory
            $res = json_model_3($pval, defined $path ? $lpath_11 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$neStrList\" [.no_index.directory]", defined $path ? $lpath_11 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.no_index.directory]", defined $path ? $lpath_11 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        push @$rep, ["unexpected prop [.no_index]", defined $path ? $lpath_11 : undef] if defined $rep;
        return 0;
    }
    return 1;
}

# check $ (.)
sub json_model_1($$$)
{
    my ($val, $path, $rep) = @_;
    # .
    unless (jm_is_object($val))
    {
        push @$rep, ["not an object [.]", $path] if defined $rep;
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        my $lpath_7 = defined $path ? [@{$path}, $prop] : undef;
        if ($prop eq "name")
        {
            # handle must name property
            $must_count++;
            # .name
            $res = json_model_2($pval, defined $path ? $lpath_7 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$neStr\" [.name]", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid mandatory prop value [.name]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "version")
        {
            # handle must version property
            $must_count++;
            # .version
            $res = jm_is_string($pval);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\" [.version]", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid mandatory prop value [.version]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "abstract")
        {
            # handle must abstract property
            $must_count++;
            # .abstract
            $res = jm_is_string($pval);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\" [.abstract]", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid mandatory prop value [.abstract]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "maintainer")
        {
            # handle must maintainer property
            $must_count++;
            # .maintainer
            # .maintainer.'|'.0
            $res = json_model_2($pval, defined $path ? $lpath_7 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$neStr\" [.maintainer.'|'.0]", defined $path ? $lpath_7 : undef] if defined $rep;
                # .maintainer.'|'.1
                $res = json_model_3($pval, defined $path ? $lpath_7 : undef, $rep);
                push @$rep, ["unexpected value for model \"\\\$neStrList\" [.maintainer.'|'.1]", defined $path ? $lpath_7 : undef] if defined $rep and not $res;
            }
            if ($res)
            {
                @$rep = () if defined $rep;
            }
            else
            {
                push @$rep, ["no model matched [.maintainer.'|']", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid mandatory prop value [.maintainer]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "license")
        {
            # handle must license property
            $must_count++;
            # .license
            # .license.'|'.0
            $res = json_model_4($pval, defined $path ? $lpath_7 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$License\" [.license.'|'.0]", defined $path ? $lpath_7 : undef] if defined $rep;
                # .license.'|'.1
                $res = json_model_5($pval, defined $path ? $lpath_7 : undef, $rep);
                unless ($res)
                {
                    push @$rep, ["unexpected value for model \"\\\$LicenseList\" [.license.'|'.1]", defined $path ? $lpath_7 : undef] if defined $rep;
                    # .license.'|'.2
                    $res = _jm_obj_3($pval, defined $path ? $lpath_7 : undef, $rep);
                    push @$rep, ["unexpected element [.license.'|'.2]", defined $path ? $lpath_7 : undef] if defined $rep and not $res;
                }
            }
            if ($res)
            {
                @$rep = () if defined $rep;
            }
            else
            {
                push @$rep, ["no model matched [.license.'|']", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid mandatory prop value [.license]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "provides")
        {
            # handle must provides property
            $must_count++;
            # .provides
            $res = _jm_obj_4($pval, defined $path ? $lpath_7 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected element [.provides]", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid mandatory prop value [.provides]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "meta-spec")
        {
            # handle must meta-spec property
            $must_count++;
            # .'meta-spec'
            $res = _jm_obj_5($pval, defined $path ? $lpath_7 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected element [.'meta-spec']", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid mandatory prop value [.'meta-spec']", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        if ($prop eq "url")
        {
            # handle may url property
            # .url
            $res = jm_is_string($pval) && jm_is_valid_url($pval, defined $path ? $lpath_7 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$URL\" [.url]", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.url]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "description")
        {
            # handle may description property
            # .description
            $res = jm_is_string($pval);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\" [.description]", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.description]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "generated_by")
        {
            # handle may generated_by property
            # .generated_by
            $res = jm_is_string($pval);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\" [.generated_by]", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.generated_by]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "tags")
        {
            # handle may tags property
            # .tags
            $res = json_model_3($pval, defined $path ? $lpath_7 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$neStrList\" [.tags]", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.tags]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "no_index")
        {
            # handle may no_index property
            # .no_index
            $res = _jm_obj_6($pval, defined $path ? $lpath_7 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected element [.no_index]", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.no_index]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "release_status")
        {
            # handle may release_status property
            # .release_status
            $res = json_model_7($pval, defined $path ? $lpath_7 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$Status\" [.release_status]", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.release_status]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "resources")
        {
            # handle may resources property
            # .resources
            $res = json_model_8($pval, defined $path ? $lpath_7 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$Resources\" [.resources]", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.resources]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        elsif ($prop eq "prereqs")
        {
            # handle may prereqs property
            # .prereqs
            $res = json_model_16($pval, defined $path ? $lpath_7 : undef, $rep);
            unless ($res)
            {
                push @$rep, ["unexpected value for model \"\\\$Prereqs\" [.prereqs]", defined $path ? $lpath_7 : undef] if defined $rep;
                push @$rep, ["invalid optional prop value [.prereqs]", defined $path ? $lpath_7 : undef] if defined $rep;
                return 0;
            }
            next;
        }
        if (_jm_re_1($prop, $path, $rep))
        {
            # handle 1 re props
            # .'/^[Xx]_/'
            $res = 1;
        }
        else
        {
            push @$rep, ["unexpected prop [.]", defined $path ? $lpath_7 : undef] if defined $rep;
            return 0;
        }
    }
    if ($must_count != 7)
    {
        if (defined $rep)
        {
            push @$rep, ["missing mandatory prop <abstract> [.]", $path] if defined $rep and not exists $$val{"abstract"};
            push @$rep, ["missing mandatory prop <license> [.]", $path] if defined $rep and not exists $$val{"license"};
            push @$rep, ["missing mandatory prop <maintainer> [.]", $path] if defined $rep and not exists $$val{"maintainer"};
            push @$rep, ["missing mandatory prop <meta-spec> [.]", $path] if defined $rep and not exists $$val{"meta-spec"};
            push @$rep, ["missing mandatory prop <name> [.]", $path] if defined $rep and not exists $$val{"name"};
            push @$rep, ["missing mandatory prop <provides> [.]", $path] if defined $rep and not exists $$val{"provides"};
            push @$rep, ["missing mandatory prop <version> [.]", $path] if defined $rep and not exists $$val{"version"};
        }
        return 0;
    }
    return 1;
}


sub jm_is_email($$$)
{
    my ($val, $path, $rep) = @_;
    my $res = $val =~ /^([-+!#\$%&'`*\/=?^{}|~_a-z0-9]+)(\.([-+!#\$%&'`*\/=?^{}|~_a-z0-9]+))*@([a-z0-9][-a-z0-9]{0,62})(\.([a-z0-9][-a-z0-9]{0,62}))*$/i;
    return $res;
}

# initialization of global variables

our $initialized = 0;

sub check_model_init()
{
    if (!$initialized)
    {
        $initialized = 1;
        %_jm_cst_0 = (
            "agpl_3" => 1,
            "apache_1_1" => 1,
            "apache_2_0" => 1,
            "artistic_1" => 1,
            "artistic_2" => 1,
            "bsd" => 1,
            "freebsd" => 1,
            "gfdl_1_2" => 1,
            "gfdl_1_3" => 1,
            "gpl_1" => 1,
            "gpl_2" => 1,
            "gpl_3" => 1,
            "lgpl_2_1" => 1,
            "lgpl_3_0" => 1,
            "mit" => 1,
            "mozilla_1_0" => 1,
            "mozilla_1_1" => 1,
            "openssl" => 1,
            "perl_5" => 1,
            "postgresql" => 1,
            "qpl_1_0" => 1,
            "ssleay" => 1,
            "sun" => 1,
            "zlib" => 1,
            "open_source" => 1,
            "restricted" => 1,
            "unrestricted" => 1,
            "unknown" => 1,
        );
        %_jm_cst_1 = (
            "stable" => 1,
            "testing" => 1,
            "unstable" => 1,
        );
        %_jm_cst_2 = (
            "configure" => 1,
            "build" => 1,
            "test" => 1,
            "runtime" => 1,
            "develop" => 1,
        );
        %_jm_cst_3 = (
            "requires" => 1,
            "recommends" => 1,
            "suggests" => 1,
            "conflicts" => 1,
        );
        %check_model_map = (
            "" => \&json_model_1,
            "neStr" => \&json_model_2,
            "neStrList" => \&json_model_3,
            "License" => \&json_model_4,
            "LicenseList" => \&json_model_5,
            "Provide" => \&json_model_6,
            "Status" => \&json_model_7,
            "Resources" => \&json_model_8,
            "SemVer" => \&json_model_9,
            "Version" => \&json_model_10,
            "Ops" => \&json_model_11,
            "VersionRange" => \&json_model_12,
            "Phase" => \&json_model_13,
            "Relation" => \&json_model_14,
            "Prereq" => \&json_model_15,
            "Prereqs" => \&json_model_16,
        );
    }
}

sub check_model_free()
{
    if ($initialized)
    {
        $initialized = 0;
        %_jm_cst_0 = ();
        %_jm_cst_1 = ();
        %_jm_cst_2 = ();
        %_jm_cst_3 = ();
        %check_model_map = ();
    }
}

sub check_model_mapper($)
{
    my ($name) = @_;
    die "unexpected model name \"$name\"" unless exists $check_model_map{$name};
    return $check_model_map{$name};
}

sub check_model($$$)
{
    my ($json, $name, $rep) = @_;
    die "unexpected model name \"$name\"" unless exists $check_model_map{$name};
    my $path = defined $rep ? [] : undef;
    return $check_model_map{$name}($json, $path, $rep);
}

#
# SCRIPT EXECUTION
#
check_model_init();
jm_main(\&check_model, \%check_model_map, JMC_VERSION);
check_model_free();
