#! /usr/bin/perl
#
# Generated by JSON Model Compiler version 2
# see https://github.com/clairey-zx81/json-model
#
use strict;
use warnings;
use re::engine::RE2;
use JSON::JsonModel;
use constant JMC_VERSION => '2';


my %_jm_obj_6_map;
my %_jm_cst_0;
my %_jm_cst_1;
my %_jm_obj_11_map;
my %_jm_obj_12_map;
my %_jm_obj_24_map;
my %_jm_obj_34_map;
my %_jm_obj_2_map;
my %check_model_map;

# check $A (.'$A')
sub json_model_2($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .'$A'
    $res = jm_is_string($val) && $val eq 'A';
    return $res;
}

# check $B (.'$B')
sub json_model_3($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .'$B'
    $res = jm_is_string($val) && $val eq 'A';
    return $res;
}

# object .'$ab'
sub _jm_obj_0($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'a')
        {
            # handle must a property
            $must_count++;
            # .'$ab'.a
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'b')
        {
            # handle must b property
            $must_count++;
            # .'$ab'.b
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    if ($must_count != 2)
    {
        return 0;
    }
    return 1;
}

# check $ab (.'$ab')
sub json_model_4($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .'$ab'
    $res = _jm_obj_0($val, $path, $rep);
    return $res;
}

# object .'$cd'
sub _jm_obj_1($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'c')
        {
            # handle must c property
            $must_count++;
            # .'$cd'.c
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'd')
        {
            # handle must d property
            $must_count++;
            # .'$cd'.d
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    if ($must_count != 2)
    {
        return 0;
    }
    return 1;
}

# check $cd (.'$cd')
sub json_model_5($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .'$cd'
    $res = _jm_obj_1($val, $path, $rep);
    return $res;
}

# object .and
sub _jm_obj_3($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'a0')
        {
            # handle may a0 property
            # .and.a0
            $res = 1;
            if ($res)
            {
                # .and.a0.'&'.0
                $res = jm_is_string($pval) && jm_is_valid_date($pval, undef, $rep);
                if ($res)
                {
                    # .and.a0.'&'.1
                    # "/^2020-/"
                    $res = jm_is_string($pval) && jm_starts_with($pval, '2020-');
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_and (.and)
sub _jm_f_0($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # conjunction, all must match
    # .and
    $res = _jm_obj_3($val, $path, $rep);
    return $res;
}

# object .array
sub _jm_obj_4($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'a0')
        {
            # handle may a0 property
            # .array.a0
            $res = jm_is_array($pval);
            if ($res)
            {
                for my $arr_0_idx (0 .. $#$pval)
                {
                    my $arr_0_item = $$pval[$arr_0_idx];
                    # .array.a0.0
                    $res = jm_is_integer($arr_0_item) && $arr_0_item >= 0;
                    if (! $res)
                    {
                        last;
                    }
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'a1')
        {
            # handle may a1 property
            # .array.a1
            $res = jm_is_array($pval);
            if ($res)
            {
                for my $arr_1_idx (0 .. $#$pval)
                {
                    my $arr_1_item = $$pval[$arr_1_idx];
                    # .array.a1.0
                    $res = jm_is_string($arr_1_item);
                    if (! $res)
                    {
                        last;
                    }
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'a2')
        {
            # handle may a2 property
            # .array.a2
            $res = jm_is_array($pval);
            if ($res)
            {
                for my $arr_2_idx (0 .. $#$pval)
                {
                    my $arr_2_item = $$pval[$arr_2_idx];
                    # .array.a2.0
                    $res = jm_is_string($arr_2_item) && jm_is_valid_date($arr_2_item, undef, $rep);
                    if (! $res)
                    {
                        last;
                    }
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'a3')
        {
            # handle may a3 property
            # .array.a3
            $res = jm_is_array($pval);
            if ($res)
            {
                for my $arr_3_idx (0 .. $#$pval)
                {
                    my $arr_3_item = $$pval[$arr_3_idx];
                    # .array.a3.0
                    $res = jm_is_boolean($arr_3_item);
                    if (! $res)
                    {
                        last;
                    }
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'a4')
        {
            # handle may a4 property
            # .array.a4
            $res = jm_is_array($pval);
            if ($res)
            {
                # accept any array
                ;
            }
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_array (.array)
sub _jm_f_1($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # example arrays
    # .array
    $res = _jm_obj_4($val, $path, $rep);
    return $res;
}

# object .bool
sub _jm_obj_5($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'b0')
        {
            # handle may b0 property
            # .bool.b0
            $res = jm_is_boolean($pval);
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'b1')
        {
            # handle may b1 property
            # .bool.b1
            $res = jm_is_boolean($pval);
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'b2')
        {
            # handle may b2 property
            # .bool.b2
            $res = jm_is_boolean($pval);
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'b3')
        {
            # handle may b3 property
            # .bool.b3
            $res = jm_is_boolean($pval) && $pval == 1;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'b4')
        {
            # handle may b4 property
            # .bool.b4
            $res = jm_is_boolean($pval) && $pval == 0;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_bool (.bool)
sub _jm_f_2($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # booleans: inference, predefs, constants
    # .bool
    $res = _jm_obj_5($val, $path, $rep);
    return $res;
}

# check _jm_obj_6_map_cia0 (.constraints.cia0)
sub _jm_f_4($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cia0
    # .constraints.cia0.'@'
    $res = jm_is_array($val);
    if ($res)
    {
        for my $arr_4_idx (0 .. $#$val)
        {
            my $arr_4_item = $$val[$arr_4_idx];
            # .constraints.cia0.'@'.0
            $res = jm_is_integer($arr_4_item) && $arr_4_item >= 0;
            if (! $res)
            {
                last;
            }
        }
    }
    if ($res)
    {
        my $ival_0 = scalar @$val;
        $res = $ival_0 == 10;
    }
    return $res;
}

# check _jm_obj_6_map_cia1 (.constraints.cia1)
sub _jm_f_5($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cia1
    # .constraints.cia1.'@'
    $res = jm_is_array($val);
    if ($res)
    {
        for my $arr_5_idx (0 .. $#$val)
        {
            my $arr_5_item = $$val[$arr_5_idx];
            # .constraints.cia1.'@'.0
            $res = jm_is_integer($arr_5_item) && $arr_5_item >= 0;
            if (! $res)
            {
                last;
            }
        }
    }
    if ($res)
    {
        my $ival_1 = scalar @$val;
        $res = $ival_1 != 10 && $ival_1 <= 15 && $ival_1 >= 5;
    }
    return $res;
}

# check _jm_obj_6_map_cia2 (.constraints.cia2)
sub _jm_f_6($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cia2
    # .constraints.cia2.'@'
    $res = jm_is_array($val);
    if ($res)
    {
        for my $arr_6_idx (0 .. $#$val)
        {
            my $arr_6_item = $$val[$arr_6_idx];
            # .constraints.cia2.'@'.0
            $res = jm_is_integer($arr_6_item) && $arr_6_item >= 0;
            if (! $res)
            {
                last;
            }
        }
    }
    if ($res)
    {
        my $ival_2 = scalar @$val;
        $res = $ival_2 <= 14 && $ival_2 >= 6;
    }
    return $res;
}

# check _jm_obj_6_map_cii0 (.constraints.cii0)
sub _jm_f_7($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cii0
    $res = jm_is_integer($val) && $val == 10;
    return $res;
}

# check _jm_obj_6_map_cii1 (.constraints.cii1)
sub _jm_f_8($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cii1
    # .constraints.cii1.'@'
    $res = jm_is_integer($val) && $val >= 0;
    if ($res)
    {
        my $ival_3 = $val;
        $res = $ival_3 != 10 && $ival_3 <= 15 && $ival_3 >= 5;
    }
    return $res;
}

# check _jm_obj_6_map_cii2 (.constraints.cii2)
sub _jm_f_9($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cii2
    # .constraints.cii2.'@'
    $res = jm_is_integer($val) && $val >= 0;
    if ($res)
    {
        my $ival_4 = $val;
        $res = $ival_4 <= 14 && $ival_4 >= 6;
    }
    return $res;
}

# check _jm_obj_6_map_cin0 (.constraints.cin0)
sub _jm_f_10($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cin0
    # .constraints.cin0.'@'
    $res = jm_is_numeric($val) && $val >= 0.0;
    if ($res)
    {
        my $fval_0 = $val;
        $res = $fval_0 == 10;
    }
    return $res;
}

# check _jm_obj_6_map_cin1 (.constraints.cin1)
sub _jm_f_11($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cin1
    # .constraints.cin1.'@'
    $res = jm_is_numeric($val) && $val >= 0.0;
    if ($res)
    {
        my $fval_1 = $val;
        $res = $fval_1 != 10 && $fval_1 <= 15 && $fval_1 >= 5;
    }
    return $res;
}

# check _jm_obj_6_map_cin2 (.constraints.cin2)
sub _jm_f_12($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cin2
    # .constraints.cin2.'@'
    $res = jm_is_numeric($val) && $val >= 0.0;
    if ($res)
    {
        my $fval_2 = $val;
        $res = $fval_2 < 15 && $fval_2 > 5;
    }
    return $res;
}

# object .constraints.cio0.'@'
sub _jm_obj_7($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        # handle other props
        # .constraints.cio0.'@'.''
        $res = jm_is_integer($pval) && $pval >= 0;
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_6_map_cio0 (.constraints.cio0)
sub _jm_f_13($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cio0
    # .constraints.cio0.'@'
    $res = _jm_obj_7($val, $path, $rep);
    if ($res)
    {
        my $ival_5 = jm_obj_size($val);
        $res = $ival_5 == 10;
    }
    return $res;
}

# object .constraints.cio1.'@'
sub _jm_obj_8($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        # handle other props
        # .constraints.cio1.'@'.''
        $res = jm_is_integer($pval) && $pval >= 0;
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_6_map_cio1 (.constraints.cio1)
sub _jm_f_14($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cio1
    # .constraints.cio1.'@'
    $res = _jm_obj_8($val, $path, $rep);
    if ($res)
    {
        my $ival_6 = jm_obj_size($val);
        $res = $ival_6 != 10 && $ival_6 <= 15 && $ival_6 >= 5;
    }
    return $res;
}

# object .constraints.cio2.'@'
sub _jm_obj_9($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        # handle other props
        # .constraints.cio2.'@'.''
        $res = jm_is_integer($pval) && $pval >= 0;
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_6_map_cio2 (.constraints.cio2)
sub _jm_f_15($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cio2
    # .constraints.cio2.'@'
    $res = _jm_obj_9($val, $path, $rep);
    if ($res)
    {
        my $ival_7 = jm_obj_size($val);
        $res = $ival_7 <= 14 && $ival_7 >= 6;
    }
    return $res;
}

# check _jm_obj_6_map_cis0 (.constraints.cis0)
sub _jm_f_16($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cis0
    # .constraints.cis0.'@'
    $res = jm_is_string($val);
    if ($res)
    {
        my $ival_8 = length $val;
        $res = $ival_8 == 10;
    }
    return $res;
}

# check _jm_obj_6_map_cis1 (.constraints.cis1)
sub _jm_f_17($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cis1
    # .constraints.cis1.'@'
    $res = jm_is_string($val);
    if ($res)
    {
        my $ival_9 = length $val;
        $res = $ival_9 != 10 && $ival_9 <= 15 && $ival_9 >= 5;
    }
    return $res;
}

# check _jm_obj_6_map_cis2 (.constraints.cis2)
sub _jm_f_18($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cis2
    # .constraints.cis2.'@'
    $res = jm_is_string($val);
    if ($res)
    {
        my $ival_10 = length $val;
        $res = $ival_10 <= 14 && $ival_10 >= 6;
    }
    return $res;
}

# check _jm_obj_6_map_cni0 (.constraints.cni0)
sub _jm_f_19($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cni0
    # .constraints.cni0.'@'
    $res = jm_is_integer($val) && $val >= 0;
    if ($res)
    {
        my $fval_3 = $val;
        $res = $fval_3 == 42.0;
    }
    return $res;
}

# check _jm_obj_6_map_cni1 (.constraints.cni1)
sub _jm_f_20($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cni1
    # .constraints.cni1.'@'
    $res = jm_is_integer($val) && $val >= 0;
    if ($res)
    {
        my $fval_4 = $val;
        $res = $fval_4 != 42.0;
    }
    return $res;
}

# check _jm_obj_6_map_cni2 (.constraints.cni2)
sub _jm_f_21($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cni2
    # .constraints.cni2.'@'
    $res = jm_is_integer($val) && $val >= 0;
    if ($res)
    {
        my $fval_5 = $val;
        $res = $fval_5 < 43.0 && $fval_5 > 42.0;
    }
    return $res;
}

# check _jm_obj_6_map_cnn0 (.constraints.cnn0)
sub _jm_f_22($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cnn0
    # .constraints.cnn0.'@'
    $res = jm_is_numeric($val) && $val >= 0.0;
    if ($res)
    {
        my $fval_6 = $val;
        $res = $fval_6 == 42.1;
    }
    return $res;
}

# check _jm_obj_6_map_cnn1 (.constraints.cnn1)
sub _jm_f_23($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cnn1
    # .constraints.cnn1.'@'
    $res = jm_is_numeric($val) && $val >= 0.0;
    if ($res)
    {
        my $fval_7 = $val;
        $res = $fval_7 != 42.1 && $fval_7 <= 99.9 && $fval_7 >= 0.1;
    }
    return $res;
}

# check _jm_obj_6_map_cnn2 (.constraints.cnn2)
sub _jm_f_24($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cnn2
    # .constraints.cnn2.'@'
    $res = jm_is_numeric($val) && $val >= 0.0;
    if ($res)
    {
        my $fval_8 = $val;
        $res = $fval_8 < 43.0 && $fval_8 > 42.0;
    }
    return $res;
}

# check _jm_obj_6_map_css0 (.constraints.css0)
sub _jm_f_25($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.css0
    # .constraints.css0.'@'
    $res = jm_is_string($val);
    if ($res)
    {
        my $sval_0 = $val;
        $res = $sval_0 eq 'Susie';
    }
    return $res;
}

# check _jm_obj_6_map_css1 (.constraints.css1)
sub _jm_f_26($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.css1
    # .constraints.css1.'@'
    $res = jm_is_string($val);
    if ($res)
    {
        my $sval_1 = $val;
        $res = $sval_1 ne 'Hobbes';
    }
    return $res;
}

# check _jm_obj_6_map_css2 (.constraints.css2)
sub _jm_f_27($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.css2
    # .constraints.css2.'@'
    $res = jm_is_string($val);
    if ($res)
    {
        my $sval_2 = $val;
        $res = $sval_2 lt 'Z' && $sval_2 gt 'A';
    }
    return $res;
}

# check _jm_obj_6_map_cua0 (.constraints.cua0)
sub _jm_f_28($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints.cua0
    # .constraints.cua0.'@'
    $res = jm_is_array($val);
    if ($res)
    {
        for my $arr_7_idx (0 .. $#$val)
        {
            my $arr_7_item = $$val[$arr_7_idx];
            # .constraints.cua0.'@'.0
            $res = jm_is_integer($arr_7_item) && $arr_7_item >= 0;
            if (! $res)
            {
                last;
            }
        }
    }
    if ($res)
    {
        $res = jm_is_unique_array($val, $path, $rep);
    }
    return $res;
}


# object .constraints
sub _jm_obj_6($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pfun;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if (($pfun = $_jm_obj_6_map{$prop}))
        {
            # handle 25 may props
            if (defined($pfun) && ! &$pfun($pval, undef, $rep))
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_constraints (.constraints)
sub _jm_f_3($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .constraints
    $res = _jm_obj_6($val, $path, $rep);
    return $res;
}



# object .enum
sub _jm_obj_10($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'e0')
        {
            # handle may e0 property
            # .enum.e0
            $res = jm_is_boolean($pval);
            if ($res)
            {
                # .enum.e0.'|'.0
                $res = $pval == 1;
                if (! $res)
                {
                    # .enum.e0.'|'.1
                    $res = $pval == 0;
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'e1')
        {
            # handle may e1 property
            # .enum.e1
            $res = jm_is_integer($pval);
            if ($res)
            {
                # .enum.e1.'|'.0
                $res = $pval == 200;
                if (! $res)
                {
                    # .enum.e1.'|'.1
                    $res = $pval == 201;
                    if (! $res)
                    {
                        # .enum.e1.'|'.2
                        $res = $pval == 204;
                    }
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'e2')
        {
            # handle may e2 property
            # .enum.e2
            $res = jm_is_scalar($pval) && jm_is_string($pval) && exists $_jm_cst_0{$pval};
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'e3')
        {
            # handle may e3 property
            # .enum.e3
            $res = jm_is_scalar($pval) && jm_is_string($pval) && exists $_jm_cst_1{$pval};
            if (! $res)
            {
                # .enum.e3.'|'.0
                $res = jm_is_integer($pval) && $pval == 42;
                if (! $res)
                {
                    # .enum.e3.'|'.1
                    $res = jm_is_boolean($pval) && $pval == 1;
                    if (! $res)
                    {
                        # .enum.e3.'|'.2
                        $res = !defined($pval);
                    }
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_enum (.enum)
sub _jm_f_29($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # an enumeration only contains constants
    # .enum
    $res = _jm_obj_10($val, $path, $rep);
    return $res;
}

# check _jm_obj_11_map_f0 (.float.f0)
sub _jm_f_31($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .float.f0
    $res = jm_is_numeric($val) && $val >= 0.0;
    return $res;
}

# check _jm_obj_11_map_f1 (.float.f1)
sub _jm_f_32($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .float.f1
    $res = jm_is_numeric($val) && $val > 0.0;
    return $res;
}

# check _jm_obj_11_map_f2 (.float.f2)
sub _jm_f_33($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .float.f2
    $res = jm_is_numeric($val);
    return $res;
}

# check _jm_obj_11_map_f3 (.float.f3)
sub _jm_f_34($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .float.f3
    $res = jm_is_numeric($val);
    return $res;
}

# check _jm_obj_11_map_f4 (.float.f4)
sub _jm_f_35($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .float.f4
    $res = jm_is_numeric($val);
    return $res;
}

# check _jm_obj_11_map_f5 (.float.f5)
sub _jm_f_36($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .float.f5
    $res = jm_is_numeric($val);
    return $res;
}

# check _jm_obj_11_map_f6 (.float.f6)
sub _jm_f_37($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .float.f6
    $res = jm_is_numeric($val) && $val == 3.1415927;
    return $res;
}

# check _jm_obj_11_map_f7 (.float.f7)
sub _jm_f_38($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .float.f7
    $res = jm_is_numeric($val) && $val == 1e+100;
    return $res;
}

# check _jm_obj_11_map_f8 (.float.f8)
sub _jm_f_39($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .float.f8
    $res = jm_is_numeric($val) && $val == -42.1;
    return $res;
}


# object .float
sub _jm_obj_11($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pfun;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if (($pfun = $_jm_obj_11_map{$prop}))
        {
            # handle 9 may props
            if (defined($pfun) && ! &$pfun($pval, undef, $rep))
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_float (.float)
sub _jm_f_30($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # floats: inference, predefs, constants
    # .float
    $res = _jm_obj_11($val, $path, $rep);
    return $res;
}

# check _jm_obj_12_map_i0 (.int.i0)
sub _jm_f_41($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .int.i0
    $res = jm_is_integer($val) && $val >= 0;
    return $res;
}

# check _jm_obj_12_map_i1 (.int.i1)
sub _jm_f_42($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .int.i1
    $res = jm_is_integer($val) && $val >= 1;
    return $res;
}

# check _jm_obj_12_map_i2 (.int.i2)
sub _jm_f_43($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .int.i2
    $res = jm_is_integer($val);
    return $res;
}

# check _jm_obj_12_map_i3 (.int.i3)
sub _jm_f_44($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .int.i3
    $res = jm_is_integer($val);
    return $res;
}

# check _jm_obj_12_map_i4 (.int.i4)
sub _jm_f_45($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .int.i4
    $res = jm_is_integer($val);
    return $res;
}

# check _jm_obj_12_map_i5 (.int.i5)
sub _jm_f_46($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .int.i5
    $res = jm_is_integer($val);
    return $res;
}

# check _jm_obj_12_map_i6 (.int.i6)
sub _jm_f_47($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .int.i6
    $res = jm_is_integer($val);
    return $res;
}

# check _jm_obj_12_map_i7 (.int.i7)
sub _jm_f_48($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .int.i7
    $res = jm_is_integer($val) && $val >= 0;
    return $res;
}

# check _jm_obj_12_map_i8 (.int.i8)
sub _jm_f_49($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .int.i8
    $res = jm_is_integer($val) && $val >= 0;
    return $res;
}

# check _jm_obj_12_map_i9 (.int.i9)
sub _jm_f_50($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .int.i9
    $res = jm_is_integer($val) && $val == 42;
    return $res;
}

# check _jm_obj_12_map_ia (.int.ia)
sub _jm_f_51($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .int.ia
    $res = jm_is_integer($val) && $val == -42;
    return $res;
}


# object .int
sub _jm_obj_12($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pfun;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if (($pfun = $_jm_obj_12_map{$prop}))
        {
            # handle 11 may props
            if (defined($pfun) && ! &$pfun($pval, undef, $rep))
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_int (.int)
sub _jm_f_40($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # integers: inference, predefs, constants
    # .int
    $res = _jm_obj_12($val, $path, $rep);
    return $res;
}

# object .merge.m0
sub _jm_obj_14($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'a')
        {
            # handle must a property
            $must_count++;
            # .merge.m0.a
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'b')
        {
            # handle may b property
            # .merge.m0.b
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    if ($must_count != 1)
    {
        return 0;
    }
    return 1;
}

# object .merge.m1.'|'.1
sub _jm_obj_15($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'a')
        {
            # handle must a property
            $must_count++;
            # .merge.m1.'|'.1.a
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'c')
        {
            # handle must c property
            $must_count++;
            # .merge.m1.'|'.1.c
            $res = jm_is_integer($pval) && $pval >= 1;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    if ($must_count != 2)
    {
        return 0;
    }
    return 1;
}

# object .merge.m1.'|'.0
sub _jm_obj_16($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'a')
        {
            # handle must a property
            $must_count++;
            # .merge.m1.'|'.0.a
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'b')
        {
            # handle must b property
            $must_count++;
            # .merge.m1.'|'.0.b
            $res = jm_is_integer($pval) && $pval >= 1;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    if ($must_count != 2)
    {
        return 0;
    }
    return 1;
}

# object .merge.m2.'|'.1
sub _jm_obj_17($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'a')
        {
            # handle must a property
            $must_count++;
            # .merge.m2.'|'.1.a
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'c')
        {
            # handle must c property
            $must_count++;
            # .merge.m2.'|'.1.c
            $res = jm_is_integer($pval) && $pval >= 1;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    if ($must_count != 2)
    {
        return 0;
    }
    return 1;
}

# object .merge.m2.'|'.0
sub _jm_obj_18($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'a')
        {
            # handle must a property
            $must_count++;
            # .merge.m2.'|'.0.a
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'b')
        {
            # handle must b property
            $must_count++;
            # .merge.m2.'|'.0.b
            $res = jm_is_integer($pval) && $pval >= 1;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    if ($must_count != 2)
    {
        return 0;
    }
    return 1;
}

# object .merge.m3.'|'.3
sub _jm_obj_19($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'b')
        {
            # handle must b property
            $must_count++;
            # .merge.m3.'|'.3.b
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'd')
        {
            # handle must d property
            $must_count++;
            # .merge.m3.'|'.3.d
            $res = jm_is_integer($pval) && $pval >= 1;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    if ($must_count != 2)
    {
        return 0;
    }
    return 1;
}

# object .merge.m3.'|'.2
sub _jm_obj_20($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'b')
        {
            # handle must b property
            $must_count++;
            # .merge.m3.'|'.2.b
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'c')
        {
            # handle must c property
            $must_count++;
            # .merge.m3.'|'.2.c
            $res = jm_is_integer($pval) && $pval >= 1;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    if ($must_count != 2)
    {
        return 0;
    }
    return 1;
}

# object .merge.m3.'|'.1
sub _jm_obj_21($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'a')
        {
            # handle must a property
            $must_count++;
            # .merge.m3.'|'.1.a
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'd')
        {
            # handle must d property
            $must_count++;
            # .merge.m3.'|'.1.d
            $res = jm_is_integer($pval) && $pval >= 1;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    if ($must_count != 2)
    {
        return 0;
    }
    return 1;
}

# object .merge.m3.'|'.0
sub _jm_obj_22($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'a')
        {
            # handle must a property
            $must_count++;
            # .merge.m3.'|'.0.a
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'c')
        {
            # handle must c property
            $must_count++;
            # .merge.m3.'|'.0.c
            $res = jm_is_integer($pval) && $pval >= 1;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    if ($must_count != 2)
    {
        return 0;
    }
    return 1;
}

# object .merge
sub _jm_obj_13($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'm0')
        {
            # handle may m0 property
            # .merge.m0
            $res = _jm_obj_14($pval, undef, $rep);
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'm1')
        {
            # handle may m1 property
            # .merge.m1
            $res = jm_is_object($pval);
            if ($res)
            {
                # .merge.m1.'|'.0
                $res = _jm_obj_16($pval, undef, $rep);
                if (! $res)
                {
                    # .merge.m1.'|'.1
                    $res = _jm_obj_15($pval, undef, $rep);
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'm2')
        {
            # handle may m2 property
            # .merge.m2
            $res = jm_is_object($pval);
            if ($res)
            {
                # .merge.m2.'|'.0
                $res = _jm_obj_18($pval, undef, $rep);
                if (! $res)
                {
                    # .merge.m2.'|'.1
                    $res = _jm_obj_17($pval, undef, $rep);
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'm3')
        {
            # handle may m3 property
            # .merge.m3
            $res = jm_is_object($pval);
            if ($res)
            {
                # .merge.m3.'|'.0
                $res = _jm_obj_22($pval, undef, $rep);
                if (! $res)
                {
                    # .merge.m3.'|'.1
                    $res = _jm_obj_21($pval, undef, $rep);
                    if (! $res)
                    {
                        # .merge.m3.'|'.2
                        $res = _jm_obj_20($pval, undef, $rep);
                        if (! $res)
                        {
                            # .merge.m3.'|'.3
                            $res = _jm_obj_19($pval, undef, $rep);
                        }
                    }
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_merge (.merge)
sub _jm_f_52($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # merge object properties
    # .merge
    $res = _jm_obj_13($val, $path, $rep);
    return $res;
}

# object .null
sub _jm_obj_23($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'n0')
        {
            # handle may n0 property
            # .null.n0
            $res = !defined($pval);
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'n1')
        {
            # handle may n1 property
            # .null.n1
            $res = !defined($pval);
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'n2')
        {
            # handle may n2 property
            # .null.n2
            $res = !defined($pval);
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_null (.null)
sub _jm_f_53($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # 3 representations of null
    # .null
    $res = _jm_obj_23($val, $path, $rep);
    return $res;
}

# object .object.o0
sub _jm_obj_25($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    if (jm_obj_size($val) == 0)
    {
        return 1;
    }
    else
    {
        return 0;
    }
}

# check _jm_obj_24_map_o0 (.object.o0)
sub _jm_f_55($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .object.o0
    $res = _jm_obj_25($val, $path, $rep);
    return $res;
}

# object .object.o1
sub _jm_obj_26($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    my $must_count = 0;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'a')
        {
            # handle must a property
            $must_count++;
            # .object.o1.a
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'b')
        {
            # handle must b property
            $must_count++;
            # .object.o1.b
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'c')
        {
            # handle must c property
            $must_count++;
            # .object.o1.c
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    if ($must_count != 3)
    {
        return 0;
    }
    return 1;
}

# check _jm_obj_24_map_o1 (.object.o1)
sub _jm_f_56($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .object.o1
    $res = _jm_obj_26($val, $path, $rep);
    return $res;
}

# object .object.o2
sub _jm_obj_27($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'a')
        {
            # handle may a property
            # .object.o2.a
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_24_map_o2 (.object.o2)
sub _jm_f_57($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .object.o2
    $res = _jm_obj_27($val, $path, $rep);
    return $res;
}

# object .object.o3
sub _jm_obj_28($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if (jm_starts_with($prop, 'a'))
        {
            # handle 1 re props
            # .object.o3.'/^a/'
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_24_map_o3 (.object.o3)
sub _jm_f_58($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .object.o3
    $res = _jm_obj_28($val, $path, $rep);
    return $res;
}

# object .object.o4
sub _jm_obj_29($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if (jm_is_string($prop) && jm_is_valid_date($prop, undef, $rep))
        {
            # handle 1 key props
            # .object.o4.'$DATE'
            $res = jm_is_string($pval);
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_24_map_o4 (.object.o4)
sub _jm_f_59($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .object.o4
    $res = _jm_obj_29($val, $path, $rep);
    return $res;
}

# object .object.o5
sub _jm_obj_30($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        # handle other props
        # .object.o5.''
        $res = jm_is_integer($pval) && $pval >= 0;
        if (! $res)
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_24_map_o5 (.object.o5)
sub _jm_f_60($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .object.o5
    $res = _jm_obj_30($val, $path, $rep);
    return $res;
}

# object .object.o6
sub _jm_obj_31($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    # accept any object
    return 1;
}

# check _jm_obj_24_map_o6 (.object.o6)
sub _jm_f_61($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .object.o6
    $res = _jm_obj_31($val, $path, $rep);
    return $res;
}


# object .object
sub _jm_obj_24($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pfun;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if (($pfun = $_jm_obj_24_map{$prop}))
        {
            # handle 7 may props
            if (defined($pfun) && ! &$pfun($pval, undef, $rep))
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_object (.object)
sub _jm_f_54($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # object map property names to values
    # .object
    $res = _jm_obj_24($val, $path, $rep);
    return $res;
}

# object .or.o2.'|'.3
sub _jm_obj_33($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    # accept any object
    return 1;
}

# object .or
sub _jm_obj_32($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'o0')
        {
            # handle may o0 property
            # .or.o0
            # .or.o0.'|'.0
            $res = jm_is_boolean($pval);
            if (! $res)
            {
                # .or.o0.'|'.1
                $res = jm_is_integer($pval);
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'o1')
        {
            # handle may o1 property
            # .or.o1
            # .or.o1.'|'.0
            $res = jm_is_string($pval) && jm_is_valid_date($pval, undef, $rep);
            if (! $res)
            {
                # .or.o1.'|'.1
                $res = jm_is_string($pval) && jm_is_valid_time($pval, undef, $rep);
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'o2')
        {
            # handle may o2 property
            # .or.o2
            # .or.o2.'|'.0
            $res = jm_is_integer($pval) && $pval >= 0;
            if (! $res)
            {
                # .or.o2.'|'.1
                $res = jm_is_string($pval) && jm_is_valid_uuid($pval, undef, $rep);
                if (! $res)
                {
                    # .or.o2.'|'.2
                    $res = jm_is_array($pval);
                    if ($res)
                    {
                        # accept any array
                        ;
                    }
                    if (! $res)
                    {
                        # .or.o2.'|'.3
                        $res = _jm_obj_33($pval, undef, $rep);
                    }
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_or (.or)
sub _jm_f_62($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # soft alternative, first match
    # .or
    $res = _jm_obj_32($val, $path, $rep);
    return $res;
}

# check _jm_obj_34_map_ANY (.predefs.ANY)
sub _jm_f_64($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.ANY
    $res = 1;
    return $res;
}

# check _jm_obj_34_map_BOOL (.predefs.BOOL)
sub _jm_f_65($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.BOOL
    $res = jm_is_boolean($val);
    return $res;
}

# check _jm_obj_34_map_BOOLEAN (.predefs.BOOLEAN)
sub _jm_f_66($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.BOOLEAN
    $res = jm_is_boolean($val);
    return $res;
}

# check _jm_obj_34_map_DATE (.predefs.DATE)
sub _jm_f_67($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.DATE
    $res = jm_is_string($val) && jm_is_valid_date($val, $path, $rep);
    return $res;
}

# check _jm_obj_34_map_DATETIME (.predefs.DATETIME)
sub _jm_f_68($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.DATETIME
    $res = jm_is_string($val) && jm_is_valid_datetime($val, $path, $rep);
    return $res;
}

# check _jm_obj_34_map_EMAIL (.predefs.EMAIL)
sub _jm_f_69($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.EMAIL
    $res = jm_is_string($val) && jm_is_valid_email($val, $path, $rep);
    return $res;
}

# check _jm_obj_34_map_EXREG (.predefs.EXREG)
sub _jm_f_70($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.EXREG
    $res = jm_is_string($val) && jm_is_valid_exreg($val, $path, $rep);
    return $res;
}

# check _jm_obj_34_map_F32 (.predefs.F32)
sub _jm_f_71($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.F32
    $res = jm_is_numeric($val);
    return $res;
}

# check _jm_obj_34_map_F64 (.predefs.F64)
sub _jm_f_72($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.F64
    $res = jm_is_numeric($val);
    return $res;
}

# check _jm_obj_34_map_FLOAT (.predefs.FLOAT)
sub _jm_f_73($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.FLOAT
    $res = jm_is_numeric($val);
    return $res;
}

# check _jm_obj_34_map_I32 (.predefs.I32)
sub _jm_f_74($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.I32
    $res = jm_is_integer($val);
    return $res;
}

# check _jm_obj_34_map_I64 (.predefs.I64)
sub _jm_f_75($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.I64
    $res = jm_is_integer($val);
    return $res;
}

# check _jm_obj_34_map_INT (.predefs.INT)
sub _jm_f_76($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.INT
    $res = jm_is_integer($val);
    return $res;
}

# check _jm_obj_34_map_INTEGER (.predefs.INTEGER)
sub _jm_f_77($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.INTEGER
    $res = jm_is_integer($val);
    return $res;
}

# check _jm_obj_34_map_JSON (.predefs.JSON)
sub _jm_f_78($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.JSON
    $res = jm_is_string($val) && jm_is_valid_json($val, $path, $rep);
    return $res;
}

# check _jm_obj_34_map_NONE (.predefs.NONE)
sub _jm_f_79($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.NONE
    $res = 0;
    return $res;
}

# check _jm_obj_34_map_NULL (.predefs.NULL)
sub _jm_f_80($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.NULL
    $res = !defined($val);
    return $res;
}

# check _jm_obj_34_map_NUMBER (.predefs.NUMBER)
sub _jm_f_81($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.NUMBER
    $res = jm_is_numeric($val);
    return $res;
}

# check _jm_obj_34_map_REGEX (.predefs.REGEX)
sub _jm_f_82($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.REGEX
    $res = jm_is_string($val) && jm_is_valid_regex($val, $path, $rep);
    return $res;
}

# check _jm_obj_34_map_STRING (.predefs.STRING)
sub _jm_f_83($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.STRING
    $res = jm_is_string($val);
    return $res;
}

# check _jm_obj_34_map_TIME (.predefs.TIME)
sub _jm_f_84($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.TIME
    $res = jm_is_string($val) && jm_is_valid_time($val, $path, $rep);
    return $res;
}

# check _jm_obj_34_map_U32 (.predefs.U32)
sub _jm_f_85($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.U32
    $res = jm_is_integer($val) && $val >= 0;
    return $res;
}

# check _jm_obj_34_map_U64 (.predefs.U64)
sub _jm_f_86($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.U64
    $res = jm_is_integer($val) && $val >= 0;
    return $res;
}

# check _jm_obj_34_map_URI (.predefs.URI)
sub _jm_f_87($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.URI
    $res = jm_is_string($val) && jm_is_valid_url($val, $path, $rep);
    return $res;
}

# check _jm_obj_34_map_URL (.predefs.URL)
sub _jm_f_88($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.URL
    $res = jm_is_string($val) && jm_is_valid_url($val, $path, $rep);
    return $res;
}

# check _jm_obj_34_map_UUID (.predefs.UUID)
sub _jm_f_89($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # .predefs.UUID
    $res = jm_is_string($val) && jm_is_valid_uuid($val, $path, $rep);
    return $res;
}


# object .predefs
sub _jm_obj_34($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pfun;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if (($pfun = $_jm_obj_34_map{$prop}))
        {
            # handle 26 may props
            if (defined($pfun) && ! &$pfun($pval, undef, $rep))
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_predefs (.predefs)
sub _jm_f_63($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # predefined models
    # .predefs
    $res = _jm_obj_34($val, $path, $rep);
    return $res;
}

sub _jm_re_0($$$)
{
    my ($val, $path, $rep) = @_;
    my $res = $val =~ /^(Calvin|Susie)$/;
    return $res;
}

# object .string
sub _jm_obj_35($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 's0')
        {
            # handle may s0 property
            # .string.s0
            $res = jm_is_string($pval);
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 's1')
        {
            # handle may s1 property
            # .string.s1
            $res = jm_is_string($pval);
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 's2')
        {
            # handle may s2 property
            # .string.s2
            $res = jm_is_string($pval) && $pval eq 'Susie';
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 's3')
        {
            # handle may s3 property
            # .string.s3
            $res = jm_is_string($pval) && $pval eq 'Calvin';
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 's4')
        {
            # handle may s4 property
            # .string.s4
            # "/^(Calvin|Susie)$/"
            $res = jm_is_string($pval) && _jm_re_0($pval, undef, $rep);
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_string (.string)
sub _jm_f_90($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # strings: inference, predef, constants, regex
    # .string
    $res = _jm_obj_35($val, $path, $rep);
    return $res;
}

# object .tuple
sub _jm_obj_36($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 't0')
        {
            # handle may t0 property
            # .tuple.t0
            $res = jm_is_array($pval) && scalar @$pval == 0;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 't1')
        {
            # handle may t1 property
            # .tuple.t1
            # .tuple.t1.'@'
            $res = jm_is_array($pval);
            if ($res)
            {
                for my $arr_8_idx (0 .. $#$pval)
                {
                    my $arr_8_item = $$pval[$arr_8_idx];
                    # .tuple.t1.'@'.0
                    $res = jm_is_integer($arr_8_item) && $arr_8_item >= 0;
                    if (! $res)
                    {
                        last;
                    }
                }
            }
            if ($res)
            {
                my $ival_11 = scalar @$pval;
                $res = $ival_11 == 1;
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 't2')
        {
            # handle may t2 property
            # .tuple.t2
            $res = jm_is_array($pval) && scalar @$pval == 2;
            if ($res)
            {
                # .tuple.t2.0
                $res = jm_is_integer($$pval[0]) && $$pval[0] >= 0;
                if ($res)
                {
                    # .tuple.t2.1
                    $res = jm_is_integer($$pval[1]) && $$pval[1] >= 0;
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 't3')
        {
            # handle may t3 property
            # .tuple.t3
            $res = jm_is_array($pval) && scalar @$pval == 3;
            if ($res)
            {
                # .tuple.t3.0
                $res = jm_is_boolean($$pval[0]);
                if ($res)
                {
                    # .tuple.t3.1
                    $res = jm_is_integer($$pval[1]) && $$pval[1] >= 0;
                    if ($res)
                    {
                        # .tuple.t3.2
                        $res = jm_is_string($$pval[2]);
                    }
                }
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 't4')
        {
            # handle may t4 property
            # .tuple.t4
            # .tuple.t4.'@'
            $res = jm_is_array($pval);
            if ($res)
            {
                my $len_0 = scalar @$pval;
                if ($len_0 > 0)
                {
                    # .tuple.t4.'@'.0
                    $res = jm_is_string($$pval[0]);
                }
                if ($res)
                {
                    for my $idx_0 (1 .. $len_0 - 1)
                    {
                        # .tuple.t4.'@'.1
                        $res = jm_is_integer($$pval[$idx_0]) && $$pval[$idx_0] >= 0;
                        if (! $res)
                        {
                            last;
                        }
                    }
                }
            }
            if ($res)
            {
                my $ival_12 = scalar @$pval;
                $res = $ival_12 >= 2;
            }
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_tuple (.tuple)
sub _jm_f_91($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # tuple items have a type
    # .tuple
    $res = _jm_obj_36($val, $path, $rep);
    return $res;
}

# object .xor
sub _jm_obj_37($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $res;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if ($prop eq 'x0')
        {
            # handle may x0 property
            # .xor.x0
            # .xor.x0.'|'.0
            $res = jm_is_boolean($pval);
            if (! $res)
            {
                # .xor.x0.'|'.1
                $res = jm_is_integer($pval);
            }
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'x1')
        {
            # handle may x1 property
            # .xor.x1
            # generic xor list
            my $xc_0 = 0;
            my $xr_0;
            # .xor.x1.'^'.0
            # "/^a/"
            $xr_0 = jm_is_string($pval) && jm_starts_with($pval, 'a');
            if ($xr_0)
            {
                $xc_0++;
            }
            # .xor.x1.'^'.1
            # "/z$/"
            $xr_0 = jm_is_string($pval) && jm_ends_with($pval, 'z');
            if ($xr_0)
            {
                $xc_0++;
            }
            $res = $xc_0 == 1;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'x2')
        {
            # handle may x2 property
            # .xor.x2
            # generic xor list
            my $xc_1 = 0;
            my $xr_1;
            # .xor.x2.'^'.0
            $xr_1 = jm_is_integer($pval);
            if ($xr_1)
            {
                $xc_1++;
            }
            # .xor.x2.'^'.1
            $xr_1 = jm_is_integer($pval) && $pval >= 0;
            if ($xr_1)
            {
                $xc_1++;
            }
            $res = $xc_1 == 1;
            if (! $res)
            {
                return 0;
            }
        }
        elsif ($prop eq 'x3')
        {
            # handle may x3 property
            # .xor.x3
            # not-case xor list
            my $is_0;
            # .xor.x3.'^'.1
            $is_0 = jm_is_integer($pval) && $pval >= 0;
            $res = ! $is_0;
            if (! $res)
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check _jm_obj_2_map_xor (.xor)
sub _jm_f_92($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # hard alternative, only one must match
    # .xor
    $res = _jm_obj_37($val, $path, $rep);
    return $res;
}


# object .
sub _jm_obj_2($$$)
{
    my ($val, $path, $rep) = @_;
    if (! jm_is_object($val))
    {
        return 0;
    }
    my $pfun;
    scalar keys %$val;
    while (my ($prop, $pval) = each %$val)
    {
        if (($pfun = $_jm_obj_2_map{$prop}))
        {
            # handle 15 may props
            if (defined($pfun) && ! &$pfun($pval, undef, $rep))
            {
                return 0;
            }
        }
        else
        {
            return 0;
        }
    }
    return 1;
}

# check $ (.)
sub json_model_1($$$)
{
    my ($val, $path, $rep) = @_;
    my $res;
    # A model to illustrate most design features
    # .
    $res = _jm_obj_2($val, $path, $rep);
    return $res;
}


# initialization of global variables

our $initialized = 0;

sub check_model_init()
{
    if (!$initialized)
    {
        $initialized = 1;
        %_jm_obj_6_map = (
            'cia0' => \&_jm_f_4,
            'cia1' => \&_jm_f_5,
            'cia2' => \&_jm_f_6,
            'cii0' => \&_jm_f_7,
            'cii1' => \&_jm_f_8,
            'cii2' => \&_jm_f_9,
            'cin0' => \&_jm_f_10,
            'cin1' => \&_jm_f_11,
            'cin2' => \&_jm_f_12,
            'cio0' => \&_jm_f_13,
            'cio1' => \&_jm_f_14,
            'cio2' => \&_jm_f_15,
            'cis0' => \&_jm_f_16,
            'cis1' => \&_jm_f_17,
            'cis2' => \&_jm_f_18,
            'cni0' => \&_jm_f_19,
            'cni1' => \&_jm_f_20,
            'cni2' => \&_jm_f_21,
            'cnn0' => \&_jm_f_22,
            'cnn1' => \&_jm_f_23,
            'cnn2' => \&_jm_f_24,
            'css0' => \&_jm_f_25,
            'css1' => \&_jm_f_26,
            'css2' => \&_jm_f_27,
            'cua0' => \&_jm_f_28,
        );
        %_jm_cst_0 = (
            'Susie' => 1,
            'Calvin' => 1,
            'Hobbes' => 1,
        );
        %_jm_cst_1 = (
            'Susie' => 1,
        );
        %_jm_obj_11_map = (
            'f0' => \&_jm_f_31,
            'f1' => \&_jm_f_32,
            'f2' => \&_jm_f_33,
            'f3' => \&_jm_f_34,
            'f4' => \&_jm_f_35,
            'f5' => \&_jm_f_36,
            'f6' => \&_jm_f_37,
            'f7' => \&_jm_f_38,
            'f8' => \&_jm_f_39,
        );
        %_jm_obj_12_map = (
            'i0' => \&_jm_f_41,
            'i1' => \&_jm_f_42,
            'i2' => \&_jm_f_43,
            'i3' => \&_jm_f_44,
            'i4' => \&_jm_f_45,
            'i5' => \&_jm_f_46,
            'i6' => \&_jm_f_47,
            'i7' => \&_jm_f_48,
            'i8' => \&_jm_f_49,
            'i9' => \&_jm_f_50,
            'ia' => \&_jm_f_51,
        );
        %_jm_obj_24_map = (
            'o0' => \&_jm_f_55,
            'o1' => \&_jm_f_56,
            'o2' => \&_jm_f_57,
            'o3' => \&_jm_f_58,
            'o4' => \&_jm_f_59,
            'o5' => \&_jm_f_60,
            'o6' => \&_jm_f_61,
        );
        %_jm_obj_34_map = (
            'ANY' => \&_jm_f_64,
            'BOOL' => \&_jm_f_65,
            'BOOLEAN' => \&_jm_f_66,
            'DATE' => \&_jm_f_67,
            'DATETIME' => \&_jm_f_68,
            'EMAIL' => \&_jm_f_69,
            'EXREG' => \&_jm_f_70,
            'F32' => \&_jm_f_71,
            'F64' => \&_jm_f_72,
            'FLOAT' => \&_jm_f_73,
            'I32' => \&_jm_f_74,
            'I64' => \&_jm_f_75,
            'INT' => \&_jm_f_76,
            'INTEGER' => \&_jm_f_77,
            'JSON' => \&_jm_f_78,
            'NONE' => \&_jm_f_79,
            'NULL' => \&_jm_f_80,
            'NUMBER' => \&_jm_f_81,
            'REGEX' => \&_jm_f_82,
            'STRING' => \&_jm_f_83,
            'TIME' => \&_jm_f_84,
            'U32' => \&_jm_f_85,
            'U64' => \&_jm_f_86,
            'URI' => \&_jm_f_87,
            'URL' => \&_jm_f_88,
            'UUID' => \&_jm_f_89,
        );
        %_jm_obj_2_map = (
            'and' => \&_jm_f_0,
            'array' => \&_jm_f_1,
            'bool' => \&_jm_f_2,
            'constraints' => \&_jm_f_3,
            'enum' => \&_jm_f_29,
            'float' => \&_jm_f_30,
            'int' => \&_jm_f_40,
            'merge' => \&_jm_f_52,
            'null' => \&_jm_f_53,
            'object' => \&_jm_f_54,
            'or' => \&_jm_f_62,
            'predefs' => \&_jm_f_63,
            'string' => \&_jm_f_90,
            'tuple' => \&_jm_f_91,
            'xor' => \&_jm_f_92,
        );
        %check_model_map = (
            '' => \&json_model_1,
            'A' => \&json_model_2,
            'B' => \&json_model_3,
            'ab' => \&json_model_4,
            'cd' => \&json_model_5,
        );
    }
}

sub check_model_free()
{
    if ($initialized)
    {
        $initialized = 0;
        %_jm_obj_6_map = ();
        %_jm_cst_0 = ();
        %_jm_cst_1 = ();
        %_jm_obj_11_map = ();
        %_jm_obj_12_map = ();
        %_jm_obj_24_map = ();
        %_jm_obj_34_map = ();
        %_jm_obj_2_map = ();
        %check_model_map = ();
    }
}

sub check_model($$$)
{
    my ($json, $name, $rep) = @_;
    die "unexpected model name \"$name\"" unless exists $check_model_map{$name};
    my $path = defined $rep ? [] : undef;
    return $check_model_map{$name}($json, $path, $rep);
}

#
# SCRIPT EXECUTION
#
check_model_init();
jm_main(\&check_model, \%check_model_map, JMC_VERSION);
check_model_free();
