# Generated for model: xoropt-006.model.json
#
# Generated by jmc (JSON Model Compiler) (https://github.com/clairey-zx81/json-model)
#

from typing import Callable
import re as re
import datetime
import urllib.parse

type Jsonable = None|bool|int|float|str|list[Jsonable]|dict[str, Jsonable]
type Path = list[str]
type Report = list[str]|None
type CheckFun = Callable[[Jsonable, str, Report], bool]
type PropMap = dict[str, CheckFun]
type TagMap = dict[None|bool|float|int|str, CheckFun]

# extract type name
def _tname(value: Jsonable) -> str:
    return type(value).__name__

# maybe add message to report
def _rep(msg: str, rep: Report) -> bool:
    rep is None or rep.append(msg)
    return False

jm_obj_0_must: PropMap
jm_obj_1_must: PropMap
# regex "/^[ab]$/"
jm_re_0 = re.compile("^[ab]$").search

# define "jm_obj_0_must_a" ($.'|'.0.a)
def jm_f_0(value: Jsonable, path: str, rep: Report = None) -> bool:
    # $.'|'.0.a
    result = isinstance(value, int) and not isinstance(value, bool) and value >= 0
    return result

# define "jm_obj_1_must_b" ($.'|'.1.b)
def jm_f_1(value: Jsonable, path: str, rep: Report = None) -> bool:
    # $.'|'.1.b
    result = isinstance(value, int) and not isinstance(value, bool) and value >= 0
    return result


# define "$None" ($.'$None')
def json_model_1(value: Jsonable, path: str, rep: Report = None) -> bool:
    # $.'$None'
    result = False
    return result


# object $.'|'.0
def jm_obj_0(value: Jsonable, path: str, rep: Report = None) -> bool:
    if not isinstance(value, dict):
        return False
    must_count = 0
    for prop, val in value.items():
        assert isinstance(prop, str)
        lpath = path + "." + prop
        if prop in jm_obj_0_must:  # must
            must_count += 1
            if not jm_obj_0_must[prop](val, lpath, rep):
                return False
        else:  # no catch all
            return False
    result = must_count == 1
    return result


# object $.'|'.1
def jm_obj_1(value: Jsonable, path: str, rep: Report = None) -> bool:
    if not isinstance(value, dict):
        return False
    must_count = 0
    for prop, val in value.items():
        assert isinstance(prop, str)
        lpath = path + "." + prop
        if prop in jm_obj_1_must:  # must
            must_count += 1
            if not jm_obj_1_must[prop](val, lpath, rep):
                return False
        else:  # no catch all
            return False
    result = must_count == 1
    return result


# object $.'|'.2
def jm_obj_2(value: Jsonable, path: str, rep: Report = None) -> bool:
    if not isinstance(value, dict):
        return False
    for prop, val in value.items():
        assert isinstance(prop, str)
        lpath = path + "." + prop
        if jm_re_0(prop) is not None:  # /^[ab]$/
            # $.'|'.2.'/^[ab]$/'
            result = False
            if not result:
                return False
        else:  # catch all
            # $.'|'.2.''
            result = isinstance(val, int) and not isinstance(val, bool) and val >= 0
            if not result:
                return False
    return True

# define "$" ($)
def json_model_0(value: Jsonable, path: str, rep: Report = None) -> bool:
    # $
    result = isinstance(value, dict)
    if result:
        # $.'|'.0
        result = jm_obj_0(value, path, rep)
        if not result:
            # $.'|'.1
            result = jm_obj_1(value, path, rep)
            if not result:
                # $.'|'.2
                result = jm_obj_2(value, path, rep)
    return result

# entry function check_model
def check_model(value: Jsonable, path: str = "$", rep: Report = None) -> bool:
    return json_model_0(value, path, rep)


# object properties maps
jm_obj_0_must = {
    "a": jm_f_0,
}
jm_obj_1_must = {
    "b": jm_f_1,
}


